/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.technojays.first.jooq.tables.interfaces.IAllianceRef;


/**
 * Alliance reference of hash generated from ordered list of teams
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "alliance_ref", schema = "first")
public class AllianceRef implements IAllianceRef {

	private static final long serialVersionUID = -1389475236;

	private Integer id;
	private String  hashRef;

	public AllianceRef() {}

	public AllianceRef(AllianceRef value) {
		this.id = value.id;
		this.hashRef = value.hashRef;
	}

	public AllianceRef(
		Integer id,
		String  hashRef
	) {
		this.id = id;
		this.hashRef = hashRef;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return this.id;
	}

	@Override
	public AllianceRef setId(Integer id) {
		this.id = id;
		return this;
	}

	@Column(name = "hash_ref", unique = true)
	@Override
	public String getHashRef() {
		return this.hashRef;
	}

	@Override
	public AllianceRef setHashRef(String hashRef) {
		this.hashRef = hashRef;
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IAllianceRef from) {
		setId(from.getId());
		setHashRef(from.getHashRef());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IAllianceRef> E into(E into) {
		into.from(this);
		return into;
	}
}
