/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.technojays.first.jooq.tables.interfaces.IAllianceType;


/**
 * Alliance types for FIRST programs
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "alliance_type", schema = "first")
public class AllianceType implements IAllianceType {

	private static final long serialVersionUID = -1621460457;

	private Integer  id;
	private String   name;
	private String[] shortName;

	public AllianceType() {}

	public AllianceType(AllianceType value) {
		this.id = value.id;
		this.name = value.name;
		this.shortName = value.shortName;
	}

	public AllianceType(
		Integer  id,
		String   name,
		String[] shortName
	) {
		this.id = id;
		this.name = name;
		this.shortName = shortName;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return this.id;
	}

	@Override
	public AllianceType setId(Integer id) {
		this.id = id;
		return this;
	}

	@Column(name = "name")
	@Override
	public String getName() {
		return this.name;
	}

	@Override
	public AllianceType setName(String name) {
		this.name = name;
		return this;
	}

	@Column(name = "short_name", unique = true)
	@Override
	public String[] getShortName() {
		return this.shortName;
	}

	@Override
	public AllianceType setShortName(String[] shortName) {
		this.shortName = shortName;
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IAllianceType from) {
		setId(from.getId());
		setName(from.getName());
		setShortName(from.getShortName());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IAllianceType> E into(E into) {
		into.from(this);
		return into;
	}
}
