/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.technojays.first.jooq.tables.interfaces.IAlliance;


/**
 * Relationship between a match and a group of allies
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "alliance", schema = "first")
public class Alliance implements IAlliance {

	private static final long serialVersionUID = -682363946;

	private Integer id;
	private Integer type;
	private Integer matchId;
	private String  allyRef;

	public Alliance() {}

	public Alliance(Alliance value) {
		this.id = value.id;
		this.type = value.type;
		this.matchId = value.matchId;
		this.allyRef = value.allyRef;
	}

	public Alliance(
		Integer id,
		Integer type,
		Integer matchId,
		String  allyRef
	) {
		this.id = id;
		this.type = type;
		this.matchId = matchId;
		this.allyRef = allyRef;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return this.id;
	}

	@Override
	public Alliance setId(Integer id) {
		this.id = id;
		return this;
	}

	@Column(name = "type", precision = 32)
	@Override
	public Integer getType() {
		return this.type;
	}

	@Override
	public Alliance setType(Integer type) {
		this.type = type;
		return this;
	}

	@Column(name = "match_id", precision = 32)
	@Override
	public Integer getMatchId() {
		return this.matchId;
	}

	@Override
	public Alliance setMatchId(Integer matchId) {
		this.matchId = matchId;
		return this;
	}

	@Column(name = "ally_ref")
	@Override
	public String getAllyRef() {
		return this.allyRef;
	}

	@Override
	public Alliance setAllyRef(String allyRef) {
		this.allyRef = allyRef;
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IAlliance from) {
		setId(from.getId());
		setType(from.getType());
		setMatchId(from.getMatchId());
		setAllyRef(from.getAllyRef());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IAlliance> E into(E into) {
		into.from(this);
		return into;
	}
}
