/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.technojays.first.jooq.tables.interfaces.IAttributeType;


/**
 * Attribute types in program
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "attribute_type", schema = "first")
public class AttributeType implements IAttributeType {

	private static final long serialVersionUID = 1163680750;

	private Integer id;
	private Object  info;

	public AttributeType() {}

	public AttributeType(AttributeType value) {
		this.id = value.id;
		this.info = value.info;
	}

	public AttributeType(
		Integer id,
		Object  info
	) {
		this.id = id;
		this.info = info;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return this.id;
	}

	@Override
	public AttributeType setId(Integer id) {
		this.id = id;
		return this;
	}

	@Column(name = "info")
	@Override
	public Object getInfo() {
		return this.info;
	}

	@Override
	public AttributeType setInfo(Object info) {
		this.info = info;
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IAttributeType from) {
		setId(from.getId());
		setInfo(from.getInfo());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IAttributeType> E into(E into) {
		into.from(this);
		return into;
	}
}
