/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.technojays.first.jooq.tables.interfaces.IAward;


/**
 * Awards awarded at competitions and events
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "award", schema = "first", uniqueConstraints = {
	@UniqueConstraint(columnNames = {"type_id", "event_id", "competition_id", "team_id"})
})
public class Award implements IAward {

	private static final long serialVersionUID = -2122134733;

	private Integer id;
	private Integer typeId;
	private Integer eventId;
	private Integer competitionId;
	private Integer teamId;
	private Integer awardeeId;

	public Award() {}

	public Award(Award value) {
		this.id = value.id;
		this.typeId = value.typeId;
		this.eventId = value.eventId;
		this.competitionId = value.competitionId;
		this.teamId = value.teamId;
		this.awardeeId = value.awardeeId;
	}

	public Award(
		Integer id,
		Integer typeId,
		Integer eventId,
		Integer competitionId,
		Integer teamId,
		Integer awardeeId
	) {
		this.id = id;
		this.typeId = typeId;
		this.eventId = eventId;
		this.competitionId = competitionId;
		this.teamId = teamId;
		this.awardeeId = awardeeId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return this.id;
	}

	@Override
	public Award setId(Integer id) {
		this.id = id;
		return this;
	}

	@Column(name = "type_id", precision = 32)
	@Override
	public Integer getTypeId() {
		return this.typeId;
	}

	@Override
	public Award setTypeId(Integer typeId) {
		this.typeId = typeId;
		return this;
	}

	@Column(name = "event_id", precision = 32)
	@Override
	public Integer getEventId() {
		return this.eventId;
	}

	@Override
	public Award setEventId(Integer eventId) {
		this.eventId = eventId;
		return this;
	}

	@Column(name = "competition_id", precision = 32)
	@Override
	public Integer getCompetitionId() {
		return this.competitionId;
	}

	@Override
	public Award setCompetitionId(Integer competitionId) {
		this.competitionId = competitionId;
		return this;
	}

	@Column(name = "team_id", precision = 32)
	@Override
	public Integer getTeamId() {
		return this.teamId;
	}

	@Override
	public Award setTeamId(Integer teamId) {
		this.teamId = teamId;
		return this;
	}

	@Column(name = "awardee_id", precision = 32)
	@Override
	public Integer getAwardeeId() {
		return this.awardeeId;
	}

	@Override
	public Award setAwardeeId(Integer awardeeId) {
		this.awardeeId = awardeeId;
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IAward from) {
		setId(from.getId());
		setTypeId(from.getTypeId());
		setEventId(from.getEventId());
		setCompetitionId(from.getCompetitionId());
		setTeamId(from.getTeamId());
		setAwardeeId(from.getAwardeeId());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IAward> E into(E into) {
		into.from(this);
		return into;
	}
}
