/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.technojays.first.jooq.tables.interfaces.ICompetition;


/**
 * A competition describes a Location, Game, and is held at an Event
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "competition", schema = "first")
public class Competition implements ICompetition {

	private static final long serialVersionUID = -1055409967;

	private Integer id;
	private String  name;
	private Integer typeId;
	private Integer eventId;
	private Integer locationId;
	private Integer gameId;

	public Competition() {}

	public Competition(Competition value) {
		this.id = value.id;
		this.name = value.name;
		this.typeId = value.typeId;
		this.eventId = value.eventId;
		this.locationId = value.locationId;
		this.gameId = value.gameId;
	}

	public Competition(
		Integer id,
		String  name,
		Integer typeId,
		Integer eventId,
		Integer locationId,
		Integer gameId
	) {
		this.id = id;
		this.name = name;
		this.typeId = typeId;
		this.eventId = eventId;
		this.locationId = locationId;
		this.gameId = gameId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return this.id;
	}

	@Override
	public Competition setId(Integer id) {
		this.id = id;
		return this;
	}

	@Column(name = "name")
	@Override
	public String getName() {
		return this.name;
	}

	@Override
	public Competition setName(String name) {
		this.name = name;
		return this;
	}

	@Column(name = "type_id", precision = 32)
	@Override
	public Integer getTypeId() {
		return this.typeId;
	}

	@Override
	public Competition setTypeId(Integer typeId) {
		this.typeId = typeId;
		return this;
	}

	@Column(name = "event_id", precision = 32)
	@Override
	public Integer getEventId() {
		return this.eventId;
	}

	@Override
	public Competition setEventId(Integer eventId) {
		this.eventId = eventId;
		return this;
	}

	@Column(name = "location_id", precision = 32)
	@Override
	public Integer getLocationId() {
		return this.locationId;
	}

	@Override
	public Competition setLocationId(Integer locationId) {
		this.locationId = locationId;
		return this;
	}

	@Column(name = "game_id", precision = 32)
	@Override
	public Integer getGameId() {
		return this.gameId;
	}

	@Override
	public Competition setGameId(Integer gameId) {
		this.gameId = gameId;
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(ICompetition from) {
		setId(from.getId());
		setName(from.getName());
		setTypeId(from.getTypeId());
		setEventId(from.getEventId());
		setLocationId(from.getLocationId());
		setGameId(from.getGameId());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends ICompetition> E into(E into) {
		into.from(this);
		return into;
	}
}
