/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.technojays.first.jooq.tables.interfaces.IEvent;


/**
 * An event describes the timeframe for competitions and celebrations that 
 * are managed together
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "event", schema = "first")
public class Event implements IEvent {

	private static final long serialVersionUID = 270926654;

	private Integer   id;
	private String    name;
	private String[]  shortName;
	private Timestamp startDate;
	private Timestamp endDate;
	private Object    info;

	public Event() {}

	public Event(Event value) {
		this.id = value.id;
		this.name = value.name;
		this.shortName = value.shortName;
		this.startDate = value.startDate;
		this.endDate = value.endDate;
		this.info = value.info;
	}

	public Event(
		Integer   id,
		String    name,
		String[]  shortName,
		Timestamp startDate,
		Timestamp endDate,
		Object    info
	) {
		this.id = id;
		this.name = name;
		this.shortName = shortName;
		this.startDate = startDate;
		this.endDate = endDate;
		this.info = info;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return this.id;
	}

	@Override
	public Event setId(Integer id) {
		this.id = id;
		return this;
	}

	@Column(name = "name")
	@Override
	public String getName() {
		return this.name;
	}

	@Override
	public Event setName(String name) {
		this.name = name;
		return this;
	}

	@Column(name = "short_name", unique = true)
	@Override
	public String[] getShortName() {
		return this.shortName;
	}

	@Override
	public Event setShortName(String[] shortName) {
		this.shortName = shortName;
		return this;
	}

	@Column(name = "start_date")
	@Override
	public Timestamp getStartDate() {
		return this.startDate;
	}

	@Override
	public Event setStartDate(Timestamp startDate) {
		this.startDate = startDate;
		return this;
	}

	@Column(name = "end_date")
	@Override
	public Timestamp getEndDate() {
		return this.endDate;
	}

	@Override
	public Event setEndDate(Timestamp endDate) {
		this.endDate = endDate;
		return this;
	}

	@Column(name = "info")
	@Override
	public Object getInfo() {
		return this.info;
	}

	@Override
	public Event setInfo(Object info) {
		this.info = info;
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IEvent from) {
		setId(from.getId());
		setName(from.getName());
		setShortName(from.getShortName());
		setStartDate(from.getStartDate());
		setEndDate(from.getEndDate());
		setInfo(from.getInfo());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IEvent> E into(E into) {
		into.from(this);
		return into;
	}
}
