/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.technojays.first.jooq.tables.interfaces.IGame;


/**
 * A game describes a specific set of rules and competitions for a program 
 * and its teams. It has a period of time 
 * associated with it.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "game", schema = "first")
public class Game implements IGame {

	private static final long serialVersionUID = -1356943689;

	private Integer   id;
	private String    name;
	private String[]  shortName;
	private Integer   programId;
	private Timestamp startDate;
	private Timestamp endDate;

	public Game() {}

	public Game(Game value) {
		this.id = value.id;
		this.name = value.name;
		this.shortName = value.shortName;
		this.programId = value.programId;
		this.startDate = value.startDate;
		this.endDate = value.endDate;
	}

	public Game(
		Integer   id,
		String    name,
		String[]  shortName,
		Integer   programId,
		Timestamp startDate,
		Timestamp endDate
	) {
		this.id = id;
		this.name = name;
		this.shortName = shortName;
		this.programId = programId;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return this.id;
	}

	@Override
	public Game setId(Integer id) {
		this.id = id;
		return this;
	}

	@Column(name = "name")
	@Override
	public String getName() {
		return this.name;
	}

	@Override
	public Game setName(String name) {
		this.name = name;
		return this;
	}

	@Column(name = "short_name", unique = true)
	@Override
	public String[] getShortName() {
		return this.shortName;
	}

	@Override
	public Game setShortName(String[] shortName) {
		this.shortName = shortName;
		return this;
	}

	@Column(name = "program_id", precision = 32)
	@Override
	public Integer getProgramId() {
		return this.programId;
	}

	@Override
	public Game setProgramId(Integer programId) {
		this.programId = programId;
		return this;
	}

	@Column(name = "start_date")
	@Override
	public Timestamp getStartDate() {
		return this.startDate;
	}

	@Override
	public Game setStartDate(Timestamp startDate) {
		this.startDate = startDate;
		return this;
	}

	@Column(name = "end_date")
	@Override
	public Timestamp getEndDate() {
		return this.endDate;
	}

	@Override
	public Game setEndDate(Timestamp endDate) {
		this.endDate = endDate;
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IGame from) {
		setId(from.getId());
		setName(from.getName());
		setShortName(from.getShortName());
		setProgramId(from.getProgramId());
		setStartDate(from.getStartDate());
		setEndDate(from.getEndDate());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IGame> E into(E into) {
		into.from(this);
		return into;
	}
}
