/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.technojays.first.jooq.tables.interfaces.ILocation;


/**
 * Locations for program
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "location", schema = "first")
public class Location implements ILocation {

	private static final long serialVersionUID = 2007360195;

	private Integer id;
	private Double  lng;
	private Double  lat;
	private Integer placeId;

	public Location() {}

	public Location(Location value) {
		this.id = value.id;
		this.lng = value.lng;
		this.lat = value.lat;
		this.placeId = value.placeId;
	}

	public Location(
		Integer id,
		Double  lng,
		Double  lat,
		Integer placeId
	) {
		this.id = id;
		this.lng = lng;
		this.lat = lat;
		this.placeId = placeId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return this.id;
	}

	@Override
	public Location setId(Integer id) {
		this.id = id;
		return this;
	}

	@Column(name = "lng", precision = 53)
	@Override
	public Double getLng() {
		return this.lng;
	}

	@Override
	public Location setLng(Double lng) {
		this.lng = lng;
		return this;
	}

	@Column(name = "lat", precision = 53)
	@Override
	public Double getLat() {
		return this.lat;
	}

	@Override
	public Location setLat(Double lat) {
		this.lat = lat;
		return this;
	}

	@Column(name = "place_id", unique = true, precision = 32)
	@Override
	public Integer getPlaceId() {
		return this.placeId;
	}

	@Override
	public Location setPlaceId(Integer placeId) {
		this.placeId = placeId;
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(ILocation from) {
		setId(from.getId());
		setLng(from.getLng());
		setLat(from.getLat());
		setPlaceId(from.getPlaceId());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends ILocation> E into(E into) {
		into.from(this);
		return into;
	}
}
