/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.technojays.first.jooq.tables.interfaces.IMatchScore;


/**
 * Scores associated with a match
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "match_score", schema = "first", uniqueConstraints = {
	@UniqueConstraint(columnNames = {"match_id", "alliance_id", "score_type_id"})
})
public class MatchScore implements IMatchScore {

	private static final long serialVersionUID = 1233352422;

	private Integer  id;
	private Integer  matchId;
	private Integer  allianceId;
	private Integer  scoreTypeId;
	private String[] value;

	public MatchScore() {}

	public MatchScore(MatchScore value) {
		this.id = value.id;
		this.matchId = value.matchId;
		this.allianceId = value.allianceId;
		this.scoreTypeId = value.scoreTypeId;
		this.value = value.value;
	}

	public MatchScore(
		Integer  id,
		Integer  matchId,
		Integer  allianceId,
		Integer  scoreTypeId,
		String[] value
	) {
		this.id = id;
		this.matchId = matchId;
		this.allianceId = allianceId;
		this.scoreTypeId = scoreTypeId;
		this.value = value;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return this.id;
	}

	@Override
	public MatchScore setId(Integer id) {
		this.id = id;
		return this;
	}

	@Column(name = "match_id", precision = 32)
	@Override
	public Integer getMatchId() {
		return this.matchId;
	}

	@Override
	public MatchScore setMatchId(Integer matchId) {
		this.matchId = matchId;
		return this;
	}

	@Column(name = "alliance_id", precision = 32)
	@Override
	public Integer getAllianceId() {
		return this.allianceId;
	}

	@Override
	public MatchScore setAllianceId(Integer allianceId) {
		this.allianceId = allianceId;
		return this;
	}

	@Column(name = "score_type_id", precision = 32)
	@Override
	public Integer getScoreTypeId() {
		return this.scoreTypeId;
	}

	@Override
	public MatchScore setScoreTypeId(Integer scoreTypeId) {
		this.scoreTypeId = scoreTypeId;
		return this;
	}

	@Column(name = "value")
	@Override
	public String[] getValue() {
		return this.value;
	}

	@Override
	public MatchScore setValue(String[] value) {
		this.value = value;
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IMatchScore from) {
		setId(from.getId());
		setMatchId(from.getMatchId());
		setAllianceId(from.getAllianceId());
		setScoreTypeId(from.getScoreTypeId());
		setValue(from.getValue());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IMatchScore> E into(E into) {
		into.from(this);
		return into;
	}
}
