/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.technojays.first.jooq.tables.interfaces.IMatch;


/**
 * Describe a match where teams competed against each other
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "match", schema = "first", uniqueConstraints = {
	@UniqueConstraint(columnNames = {"competition_id", "match_number"})
})
public class Match implements IMatch {

	private static final long serialVersionUID = 1601641901;

	private Integer   id;
	private Integer   matchNumber;
	private Integer   competitionId;
	private Timestamp startTime;
	private Timestamp endTime;

	public Match() {}

	public Match(Match value) {
		this.id = value.id;
		this.matchNumber = value.matchNumber;
		this.competitionId = value.competitionId;
		this.startTime = value.startTime;
		this.endTime = value.endTime;
	}

	public Match(
		Integer   id,
		Integer   matchNumber,
		Integer   competitionId,
		Timestamp startTime,
		Timestamp endTime
	) {
		this.id = id;
		this.matchNumber = matchNumber;
		this.competitionId = competitionId;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return this.id;
	}

	@Override
	public Match setId(Integer id) {
		this.id = id;
		return this;
	}

	@Column(name = "match_number", precision = 32)
	@Override
	public Integer getMatchNumber() {
		return this.matchNumber;
	}

	@Override
	public Match setMatchNumber(Integer matchNumber) {
		this.matchNumber = matchNumber;
		return this;
	}

	@Column(name = "competition_id", precision = 32)
	@Override
	public Integer getCompetitionId() {
		return this.competitionId;
	}

	@Override
	public Match setCompetitionId(Integer competitionId) {
		this.competitionId = competitionId;
		return this;
	}

	@Column(name = "start_time")
	@Override
	public Timestamp getStartTime() {
		return this.startTime;
	}

	@Override
	public Match setStartTime(Timestamp startTime) {
		this.startTime = startTime;
		return this;
	}

	@Column(name = "end_time")
	@Override
	public Timestamp getEndTime() {
		return this.endTime;
	}

	@Override
	public Match setEndTime(Timestamp endTime) {
		this.endTime = endTime;
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IMatch from) {
		setId(from.getId());
		setMatchNumber(from.getMatchNumber());
		setCompetitionId(from.getCompetitionId());
		setStartTime(from.getStartTime());
		setEndTime(from.getEndTime());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IMatch> E into(E into) {
		into.from(this);
		return into;
	}
}
