/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.technojays.first.jooq.tables.interfaces.IProgram;


/**
 * A program is a sub-organization of FIRST that describes the type of games 
 * that will be played and the 
 * types of participants.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "program", schema = "first")
public class Program implements IProgram {

	private static final long serialVersionUID = 1678877419;

	private Integer  id;
	private String   name;
	private String[] shortName;
	private String[] membership;
	private Object   info;

	public Program() {}

	public Program(Program value) {
		this.id = value.id;
		this.name = value.name;
		this.shortName = value.shortName;
		this.membership = value.membership;
		this.info = value.info;
	}

	public Program(
		Integer  id,
		String   name,
		String[] shortName,
		String[] membership,
		Object   info
	) {
		this.id = id;
		this.name = name;
		this.shortName = shortName;
		this.membership = membership;
		this.info = info;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return this.id;
	}

	@Override
	public Program setId(Integer id) {
		this.id = id;
		return this;
	}

	@Column(name = "name")
	@Override
	public String getName() {
		return this.name;
	}

	@Override
	public Program setName(String name) {
		this.name = name;
		return this;
	}

	@Column(name = "short_name", unique = true)
	@Override
	public String[] getShortName() {
		return this.shortName;
	}

	@Override
	public Program setShortName(String[] shortName) {
		this.shortName = shortName;
		return this;
	}

	@Column(name = "membership")
	@Override
	public String[] getMembership() {
		return this.membership;
	}

	@Override
	public Program setMembership(String[] membership) {
		this.membership = membership;
		return this;
	}

	@Column(name = "info")
	@Override
	public Object getInfo() {
		return this.info;
	}

	@Override
	public Program setInfo(Object info) {
		this.info = info;
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IProgram from) {
		setId(from.getId());
		setName(from.getName());
		setShortName(from.getShortName());
		setMembership(from.getMembership());
		setInfo(from.getInfo());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IProgram> E into(E into) {
		into.from(this);
		return into;
	}
}
