/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.technojays.first.jooq.tables.interfaces.ISponsor;


/**
 * Sponsors for teams, events, groups, programs, etc
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "sponsor", schema = "first")
public class Sponsor implements ISponsor {

	private static final long serialVersionUID = -1689788003;

	private Integer id;
	private Object  info;

	public Sponsor() {}

	public Sponsor(Sponsor value) {
		this.id = value.id;
		this.info = value.info;
	}

	public Sponsor(
		Integer id,
		Object  info
	) {
		this.id = id;
		this.info = info;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return this.id;
	}

	@Override
	public Sponsor setId(Integer id) {
		this.id = id;
		return this;
	}

	@Column(name = "info")
	@Override
	public Object getInfo() {
		return this.info;
	}

	@Override
	public Sponsor setInfo(Object info) {
		this.info = info;
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(ISponsor from) {
		setId(from.getId());
		setInfo(from.getInfo());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends ISponsor> E into(E into) {
		into.from(this);
		return into;
	}
}
