/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.technojays.first.jooq.tables.interfaces.ITeam;


/**
 * A team associated with a specific FIRST program
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "team", schema = "first")
public class Team implements ITeam {

	private static final long serialVersionUID = -2127098984;

	private Integer id;
	private Integer programId;
	private Integer number;
	private String  name;
	private String  shortName;

	public Team() {}

	public Team(Team value) {
		this.id = value.id;
		this.programId = value.programId;
		this.number = value.number;
		this.name = value.name;
		this.shortName = value.shortName;
	}

	public Team(
		Integer id,
		Integer programId,
		Integer number,
		String  name,
		String  shortName
	) {
		this.id = id;
		this.programId = programId;
		this.number = number;
		this.name = name;
		this.shortName = shortName;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return this.id;
	}

	@Override
	public Team setId(Integer id) {
		this.id = id;
		return this;
	}

	@Column(name = "program_id", precision = 32)
	@Override
	public Integer getProgramId() {
		return this.programId;
	}

	@Override
	public Team setProgramId(Integer programId) {
		this.programId = programId;
		return this;
	}

	@Column(name = "number", unique = true, precision = 32)
	@Override
	public Integer getNumber() {
		return this.number;
	}

	@Override
	public Team setNumber(Integer number) {
		this.number = number;
		return this;
	}

	@Column(name = "name")
	@Override
	public String getName() {
		return this.name;
	}

	@Override
	public Team setName(String name) {
		this.name = name;
		return this;
	}

	@Column(name = "short_name")
	@Override
	public String getShortName() {
		return this.shortName;
	}

	@Override
	public Team setShortName(String shortName) {
		this.shortName = shortName;
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(ITeam from) {
		setId(from.getId());
		setProgramId(from.getProgramId());
		setNumber(from.getNumber());
		setName(from.getName());
		setShortName(from.getShortName());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends ITeam> E into(E into) {
		into.from(this);
		return into;
	}
}
