/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.technojays.first.jooq.tables.interfaces.ITeamSponsor;


/**
 * Sponsors associated with a FIRST team for a given game (season)
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "team_sponsor", schema = "first", uniqueConstraints = {
	@UniqueConstraint(columnNames = {"team_id", "sponsor_id", "game_id"})
})
public class TeamSponsor implements ITeamSponsor {

	private static final long serialVersionUID = 1900238764;

	private Integer id;
	private Integer teamId;
	private Integer sponsorId;
	private Integer gameId;

	public TeamSponsor() {}

	public TeamSponsor(TeamSponsor value) {
		this.id = value.id;
		this.teamId = value.teamId;
		this.sponsorId = value.sponsorId;
		this.gameId = value.gameId;
	}

	public TeamSponsor(
		Integer id,
		Integer teamId,
		Integer sponsorId,
		Integer gameId
	) {
		this.id = id;
		this.teamId = teamId;
		this.sponsorId = sponsorId;
		this.gameId = gameId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return this.id;
	}

	@Override
	public TeamSponsor setId(Integer id) {
		this.id = id;
		return this;
	}

	@Column(name = "team_id", precision = 32)
	@Override
	public Integer getTeamId() {
		return this.teamId;
	}

	@Override
	public TeamSponsor setTeamId(Integer teamId) {
		this.teamId = teamId;
		return this;
	}

	@Column(name = "sponsor_id", precision = 32)
	@Override
	public Integer getSponsorId() {
		return this.sponsorId;
	}

	@Override
	public TeamSponsor setSponsorId(Integer sponsorId) {
		this.sponsorId = sponsorId;
		return this;
	}

	@Column(name = "game_id", precision = 32)
	@Override
	public Integer getGameId() {
		return this.gameId;
	}

	@Override
	public TeamSponsor setGameId(Integer gameId) {
		this.gameId = gameId;
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(ITeamSponsor from) {
		setId(from.getId());
		setTeamId(from.getTeamId());
		setSponsorId(from.getSponsorId());
		setGameId(from.getGameId());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends ITeamSponsor> E into(E into) {
		into.from(this);
		return into;
	}
}
