/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.records;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.technojays.first.jooq.tables.AllianceRef;
import org.technojays.first.jooq.tables.interfaces.IAllianceRef;


/**
 * Alliance reference of hash generated from ordered list of teams
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "alliance_ref", schema = "first")
public class AllianceRefRecord extends UpdatableRecordImpl<AllianceRefRecord> implements Record2<Integer, String>, IAllianceRef {

	private static final long serialVersionUID = -1217371591;

	/**
	 * Setter for <code>first.alliance_ref.id</code>. Alliance ref id
	 */
	@Override
	public AllianceRefRecord setId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>first.alliance_ref.id</code>. Alliance ref id
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>first.alliance_ref.hash_ref</code>. Hash of ordered team numbers for this alliance
	 */
	@Override
	public AllianceRefRecord setHashRef(String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>first.alliance_ref.hash_ref</code>. Hash of ordered team numbers for this alliance
	 */
	@Column(name = "hash_ref", unique = true)
	@Override
	public String getHashRef() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return AllianceRef.ALLIANCE_REF.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return AllianceRef.ALLIANCE_REF.HASH_REF;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getHashRef();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AllianceRefRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AllianceRefRecord value2(String value) {
		setHashRef(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AllianceRefRecord values(Integer value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IAllianceRef from) {
		setId(from.getId());
		setHashRef(from.getHashRef());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IAllianceRef> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AllianceRefRecord
	 */
	public AllianceRefRecord() {
		super(AllianceRef.ALLIANCE_REF);
	}

	/**
	 * Create a detached, initialised AllianceRefRecord
	 */
	public AllianceRefRecord(Integer id, String hashRef) {
		super(AllianceRef.ALLIANCE_REF);

		setValue(0, id);
		setValue(1, hashRef);
	}
}
