/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.records;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.technojays.first.jooq.tables.MatchScore;
import org.technojays.first.jooq.tables.interfaces.IMatchScore;


/**
 * Scores associated with a match
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "match_score", schema = "first", uniqueConstraints = {
	@UniqueConstraint(columnNames = {"match_id", "alliance_id", "score_type_id"})
})
public class MatchScoreRecord extends UpdatableRecordImpl<MatchScoreRecord> implements Record5<Integer, Integer, Integer, Integer, String[]>, IMatchScore {

	private static final long serialVersionUID = -488370810;

	/**
	 * Setter for <code>first.match_score.id</code>. system id for this match
	 */
	@Override
	public MatchScoreRecord setId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>first.match_score.id</code>. system id for this match
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>first.match_score.match_id</code>. system id of the associated match
	 */
	@Override
	public MatchScoreRecord setMatchId(Integer value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>first.match_score.match_id</code>. system id of the associated match
	 */
	@Column(name = "match_id", precision = 32)
	@Override
	public Integer getMatchId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>first.match_score.alliance_id</code>. system id of the associated alliance
	 */
	@Override
	public MatchScoreRecord setAllianceId(Integer value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>first.match_score.alliance_id</code>. system id of the associated alliance
	 */
	@Column(name = "alliance_id", precision = 32)
	@Override
	public Integer getAllianceId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>first.match_score.score_type_id</code>. system id of the score type
	 */
	@Override
	public MatchScoreRecord setScoreTypeId(Integer value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>first.match_score.score_type_id</code>. system id of the score type
	 */
	@Column(name = "score_type_id", precision = 32)
	@Override
	public Integer getScoreTypeId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>first.match_score.value</code>. score value
	 */
	@Override
	public MatchScoreRecord setValue(String[] value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>first.match_score.value</code>. score value
	 */
	@Column(name = "value")
	@Override
	public String[] getValue() {
		return (String[]) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, Integer, Integer, String[]> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, Integer, Integer, String[]> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return MatchScore.MATCH_SCORE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return MatchScore.MATCH_SCORE.MATCH_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return MatchScore.MATCH_SCORE.ALLIANCE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return MatchScore.MATCH_SCORE.SCORE_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String[]> field5() {
		return MatchScore.MATCH_SCORE.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getMatchId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getAllianceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getScoreTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String[] value5() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MatchScoreRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MatchScoreRecord value2(Integer value) {
		setMatchId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MatchScoreRecord value3(Integer value) {
		setAllianceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MatchScoreRecord value4(Integer value) {
		setScoreTypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MatchScoreRecord value5(String[] value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MatchScoreRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String[] value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IMatchScore from) {
		setId(from.getId());
		setMatchId(from.getMatchId());
		setAllianceId(from.getAllianceId());
		setScoreTypeId(from.getScoreTypeId());
		setValue(from.getValue());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IMatchScore> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MatchScoreRecord
	 */
	public MatchScoreRecord() {
		super(MatchScore.MATCH_SCORE);
	}

	/**
	 * Create a detached, initialised MatchScoreRecord
	 */
	public MatchScoreRecord(Integer id, Integer matchId, Integer allianceId, Integer scoreTypeId, String[] value) {
		super(MatchScore.MATCH_SCORE);

		setValue(0, id);
		setValue(1, matchId);
		setValue(2, allianceId);
		setValue(3, scoreTypeId);
		setValue(4, value);
	}
}
