/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.records;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.technojays.first.jooq.tables.Program;
import org.technojays.first.jooq.tables.interfaces.IProgram;


/**
 * A program is a sub-organization of FIRST that describes the type of games 
 * that will be played and the 
 * types of participants.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "program", schema = "first")
public class ProgramRecord extends UpdatableRecordImpl<ProgramRecord> implements Record5<Integer, String, String[], String[], Object>, IProgram {

	private static final long serialVersionUID = -774679298;

	/**
	 * Setter for <code>first.program.id</code>. system id for this program
	 */
	@Override
	public ProgramRecord setId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>first.program.id</code>. system id for this program
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>first.program.name</code>. Display name for this program
	 */
	@Override
	public ProgramRecord setName(String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>first.program.name</code>. Display name for this program
	 */
	@Column(name = "name")
	@Override
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>first.program.short_name</code>. symbolic / abbreviate name used in program searches
	 */
	@Override
	public ProgramRecord setShortName(String[] value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>first.program.short_name</code>. symbolic / abbreviate name used in program searches
	 */
	@Column(name = "short_name", unique = true)
	@Override
	public String[] getShortName() {
		return (String[]) getValue(2);
	}

	/**
	 * Setter for <code>first.program.membership</code>. Student body participation in this program
	 */
	@Override
	public ProgramRecord setMembership(String[] value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>first.program.membership</code>. Student body participation in this program
	 */
	@Column(name = "membership")
	@Override
	public String[] getMembership() {
		return (String[]) getValue(3);
	}

	/**
	 * Setter for <code>first.program.info</code>. Info for this program
	 */
	@Override
	public ProgramRecord setInfo(Object value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>first.program.info</code>. Info for this program
	 */
	@Column(name = "info")
	@Override
	public Object getInfo() {
		return (Object) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, String[], String[], Object> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, String[], String[], Object> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Program.PROGRAM.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Program.PROGRAM.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String[]> field3() {
		return Program.PROGRAM.SHORT_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String[]> field4() {
		return Program.PROGRAM.MEMBERSHIP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Object> field5() {
		return Program.PROGRAM.INFO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String[] value3() {
		return getShortName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String[] value4() {
		return getMembership();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Object value5() {
		return getInfo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProgramRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProgramRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProgramRecord value3(String[] value) {
		setShortName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProgramRecord value4(String[] value) {
		setMembership(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProgramRecord value5(Object value) {
		setInfo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProgramRecord values(Integer value1, String value2, String[] value3, String[] value4, Object value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IProgram from) {
		setId(from.getId());
		setName(from.getName());
		setShortName(from.getShortName());
		setMembership(from.getMembership());
		setInfo(from.getInfo());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IProgram> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ProgramRecord
	 */
	public ProgramRecord() {
		super(Program.PROGRAM);
	}

	/**
	 * Create a detached, initialised ProgramRecord
	 */
	public ProgramRecord(Integer id, String name, String[] shortName, String[] membership, Object info) {
		super(Program.PROGRAM);

		setValue(0, id);
		setValue(1, name);
		setValue(2, shortName);
		setValue(3, membership);
		setValue(4, info);
	}
}
