/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.records;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.technojays.first.jooq.tables.Sponsor;
import org.technojays.first.jooq.tables.interfaces.ISponsor;


/**
 * Sponsors for teams, events, groups, programs, etc
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "sponsor", schema = "first")
public class SponsorRecord extends UpdatableRecordImpl<SponsorRecord> implements Record2<Integer, Object>, ISponsor {

	private static final long serialVersionUID = 1521517796;

	/**
	 * Setter for <code>first.sponsor.id</code>. system id for this sponsor
	 */
	@Override
	public SponsorRecord setId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>first.sponsor.id</code>. system id for this sponsor
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@Override
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>first.sponsor.info</code>. sponsor information
	 */
	@Override
	public SponsorRecord setInfo(Object value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>first.sponsor.info</code>. sponsor information
	 */
	@Column(name = "info")
	@Override
	public Object getInfo() {
		return (Object) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Object> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Object> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Sponsor.SPONSOR.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Object> field2() {
		return Sponsor.SPONSOR.INFO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Object value2() {
		return getInfo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SponsorRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SponsorRecord value2(Object value) {
		setInfo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SponsorRecord values(Integer value1, Object value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(ISponsor from) {
		setId(from.getId());
		setInfo(from.getInfo());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends ISponsor> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SponsorRecord
	 */
	public SponsorRecord() {
		super(Sponsor.SPONSOR);
	}

	/**
	 * Create a detached, initialised SponsorRecord
	 */
	public SponsorRecord(Integer id, Object info) {
		super(Sponsor.SPONSOR);

		setValue(0, id);
		setValue(1, info);
	}
}
