/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Alliance reference of hash generated from ordered list of teams
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllianceRef implements Serializable {

	private static final long serialVersionUID = -389800032;

	private Integer id;
	private String  hashRef;

	public AllianceRef() {}

	public AllianceRef(AllianceRef value) {
		this.id = value.id;
		this.hashRef = value.hashRef;
	}

	public AllianceRef(
		Integer id,
		String  hashRef
	) {
		this.id = id;
		this.hashRef = hashRef;
	}

	public Integer getId() {
		return this.id;
	}

	public AllianceRef setId(Integer id) {
		this.id = id;
		return this;
	}

	public String getHashRef() {
		return this.hashRef;
	}

	public AllianceRef setHashRef(String hashRef) {
		this.hashRef = hashRef;
		return this;
	}
}
