/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Alliance types for FIRST programs
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllianceType implements Serializable {

	private static final long serialVersionUID = 39495692;

	private Integer  id;
	private String   name;
	private String[] shortName;

	public AllianceType() {}

	public AllianceType(AllianceType value) {
		this.id = value.id;
		this.name = value.name;
		this.shortName = value.shortName;
	}

	public AllianceType(
		Integer  id,
		String   name,
		String[] shortName
	) {
		this.id = id;
		this.name = name;
		this.shortName = shortName;
	}

	public Integer getId() {
		return this.id;
	}

	public AllianceType setId(Integer id) {
		this.id = id;
		return this;
	}

	public String getName() {
		return this.name;
	}

	public AllianceType setName(String name) {
		this.name = name;
		return this;
	}

	public String[] getShortName() {
		return this.shortName;
	}

	public AllianceType setShortName(String[] shortName) {
		this.shortName = shortName;
		return this;
	}
}
