/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Relationship between a match and a group of allies
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Alliance implements Serializable {

	private static final long serialVersionUID = 1053560379;

	private Integer id;
	private Integer type;
	private Integer matchId;
	private String  allyRef;

	public Alliance() {}

	public Alliance(Alliance value) {
		this.id = value.id;
		this.type = value.type;
		this.matchId = value.matchId;
		this.allyRef = value.allyRef;
	}

	public Alliance(
		Integer id,
		Integer type,
		Integer matchId,
		String  allyRef
	) {
		this.id = id;
		this.type = type;
		this.matchId = matchId;
		this.allyRef = allyRef;
	}

	public Integer getId() {
		return this.id;
	}

	public Alliance setId(Integer id) {
		this.id = id;
		return this;
	}

	public Integer getType() {
		return this.type;
	}

	public Alliance setType(Integer type) {
		this.type = type;
		return this;
	}

	public Integer getMatchId() {
		return this.matchId;
	}

	public Alliance setMatchId(Integer matchId) {
		this.matchId = matchId;
		return this;
	}

	public String getAllyRef() {
		return this.allyRef;
	}

	public Alliance setAllyRef(String allyRef) {
		this.allyRef = allyRef;
		return this;
	}
}
