/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Relationship between a set of teams for an alliance
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ally implements Serializable {

	private static final long serialVersionUID = 917514835;

	private Integer  id;
	private Integer  teamId;
	private String[] allyRef;

	public Ally() {}

	public Ally(Ally value) {
		this.id = value.id;
		this.teamId = value.teamId;
		this.allyRef = value.allyRef;
	}

	public Ally(
		Integer  id,
		Integer  teamId,
		String[] allyRef
	) {
		this.id = id;
		this.teamId = teamId;
		this.allyRef = allyRef;
	}

	public Integer getId() {
		return this.id;
	}

	public Ally setId(Integer id) {
		this.id = id;
		return this;
	}

	public Integer getTeamId() {
		return this.teamId;
	}

	public Ally setTeamId(Integer teamId) {
		this.teamId = teamId;
		return this;
	}

	public String[] getAllyRef() {
		return this.allyRef;
	}

	public Ally setAllyRef(String[] allyRef) {
		this.allyRef = allyRef;
		return this;
	}
}
