/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Attribute types in program
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AttributeType implements Serializable {

	private static final long serialVersionUID = -493205500;

	private Integer id;
	private Object  info;

	public AttributeType() {}

	public AttributeType(AttributeType value) {
		this.id = value.id;
		this.info = value.info;
	}

	public AttributeType(
		Integer id,
		Object  info
	) {
		this.id = id;
		this.info = info;
	}

	public Integer getId() {
		return this.id;
	}

	public AttributeType setId(Integer id) {
		this.id = id;
		return this;
	}

	public Object getInfo() {
		return this.info;
	}

	public AttributeType setInfo(Object info) {
		this.info = info;
		return this;
	}
}
