/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Award types
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AwardType implements Serializable {

	private static final long serialVersionUID = 1645145671;

	private Integer id;
	private Object  info;

	public AwardType() {}

	public AwardType(AwardType value) {
		this.id = value.id;
		this.info = value.info;
	}

	public AwardType(
		Integer id,
		Object  info
	) {
		this.id = id;
		this.info = info;
	}

	public Integer getId() {
		return this.id;
	}

	public AwardType setId(Integer id) {
		this.id = id;
		return this;
	}

	public Object getInfo() {
		return this.info;
	}

	public AwardType setInfo(Object info) {
		this.info = info;
		return this;
	}
}
