/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Awards awarded at competitions and events
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Award implements Serializable {

	private static final long serialVersionUID = 931539790;

	private Integer id;
	private Integer typeId;
	private Integer eventId;
	private Integer competitionId;
	private Integer teamId;
	private Integer awardeeId;

	public Award() {}

	public Award(Award value) {
		this.id = value.id;
		this.typeId = value.typeId;
		this.eventId = value.eventId;
		this.competitionId = value.competitionId;
		this.teamId = value.teamId;
		this.awardeeId = value.awardeeId;
	}

	public Award(
		Integer id,
		Integer typeId,
		Integer eventId,
		Integer competitionId,
		Integer teamId,
		Integer awardeeId
	) {
		this.id = id;
		this.typeId = typeId;
		this.eventId = eventId;
		this.competitionId = competitionId;
		this.teamId = teamId;
		this.awardeeId = awardeeId;
	}

	public Integer getId() {
		return this.id;
	}

	public Award setId(Integer id) {
		this.id = id;
		return this;
	}

	public Integer getTypeId() {
		return this.typeId;
	}

	public Award setTypeId(Integer typeId) {
		this.typeId = typeId;
		return this;
	}

	public Integer getEventId() {
		return this.eventId;
	}

	public Award setEventId(Integer eventId) {
		this.eventId = eventId;
		return this;
	}

	public Integer getCompetitionId() {
		return this.competitionId;
	}

	public Award setCompetitionId(Integer competitionId) {
		this.competitionId = competitionId;
		return this;
	}

	public Integer getTeamId() {
		return this.teamId;
	}

	public Award setTeamId(Integer teamId) {
		this.teamId = teamId;
		return this;
	}

	public Integer getAwardeeId() {
		return this.awardeeId;
	}

	public Award setAwardeeId(Integer awardeeId) {
		this.awardeeId = awardeeId;
		return this;
	}
}
