/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * An event describes the timeframe for competitions and celebrations that 
 * are managed together
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Event implements Serializable {

	private static final long serialVersionUID = -1012618219;

	private Integer   id;
	private String    name;
	private String[]  shortName;
	private Timestamp startDate;
	private Timestamp endDate;
	private Object    info;

	public Event() {}

	public Event(Event value) {
		this.id = value.id;
		this.name = value.name;
		this.shortName = value.shortName;
		this.startDate = value.startDate;
		this.endDate = value.endDate;
		this.info = value.info;
	}

	public Event(
		Integer   id,
		String    name,
		String[]  shortName,
		Timestamp startDate,
		Timestamp endDate,
		Object    info
	) {
		this.id = id;
		this.name = name;
		this.shortName = shortName;
		this.startDate = startDate;
		this.endDate = endDate;
		this.info = info;
	}

	public Integer getId() {
		return this.id;
	}

	public Event setId(Integer id) {
		this.id = id;
		return this;
	}

	public String getName() {
		return this.name;
	}

	public Event setName(String name) {
		this.name = name;
		return this;
	}

	public String[] getShortName() {
		return this.shortName;
	}

	public Event setShortName(String[] shortName) {
		this.shortName = shortName;
		return this;
	}

	public Timestamp getStartDate() {
		return this.startDate;
	}

	public Event setStartDate(Timestamp startDate) {
		this.startDate = startDate;
		return this;
	}

	public Timestamp getEndDate() {
		return this.endDate;
	}

	public Event setEndDate(Timestamp endDate) {
		this.endDate = endDate;
		return this;
	}

	public Object getInfo() {
		return this.info;
	}

	public Event setInfo(Object info) {
		this.info = info;
		return this;
	}
}
