/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Scores associated with a match
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MatchScore implements Serializable {

	private static final long serialVersionUID = -551739297;

	private Integer  id;
	private Integer  matchId;
	private Integer  allianceId;
	private Integer  scoreTypeId;
	private String[] value;

	public MatchScore() {}

	public MatchScore(MatchScore value) {
		this.id = value.id;
		this.matchId = value.matchId;
		this.allianceId = value.allianceId;
		this.scoreTypeId = value.scoreTypeId;
		this.value = value.value;
	}

	public MatchScore(
		Integer  id,
		Integer  matchId,
		Integer  allianceId,
		Integer  scoreTypeId,
		String[] value
	) {
		this.id = id;
		this.matchId = matchId;
		this.allianceId = allianceId;
		this.scoreTypeId = scoreTypeId;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public MatchScore setId(Integer id) {
		this.id = id;
		return this;
	}

	public Integer getMatchId() {
		return this.matchId;
	}

	public MatchScore setMatchId(Integer matchId) {
		this.matchId = matchId;
		return this;
	}

	public Integer getAllianceId() {
		return this.allianceId;
	}

	public MatchScore setAllianceId(Integer allianceId) {
		this.allianceId = allianceId;
		return this;
	}

	public Integer getScoreTypeId() {
		return this.scoreTypeId;
	}

	public MatchScore setScoreTypeId(Integer scoreTypeId) {
		this.scoreTypeId = scoreTypeId;
		return this;
	}

	public String[] getValue() {
		return this.value;
	}

	public MatchScore setValue(String[] value) {
		this.value = value;
		return this;
	}
}
