/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * A program is a sub-organization of FIRST that describes the type of games 
 * that will be played and the 
 * types of participants.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Program implements Serializable {

	private static final long serialVersionUID = -1961666020;

	private Integer  id;
	private String   name;
	private String[] shortName;
	private String[] membership;
	private Object   info;

	public Program() {}

	public Program(Program value) {
		this.id = value.id;
		this.name = value.name;
		this.shortName = value.shortName;
		this.membership = value.membership;
		this.info = value.info;
	}

	public Program(
		Integer  id,
		String   name,
		String[] shortName,
		String[] membership,
		Object   info
	) {
		this.id = id;
		this.name = name;
		this.shortName = shortName;
		this.membership = membership;
		this.info = info;
	}

	public Integer getId() {
		return this.id;
	}

	public Program setId(Integer id) {
		this.id = id;
		return this;
	}

	public String getName() {
		return this.name;
	}

	public Program setName(String name) {
		this.name = name;
		return this;
	}

	public String[] getShortName() {
		return this.shortName;
	}

	public Program setShortName(String[] shortName) {
		this.shortName = shortName;
		return this;
	}

	public String[] getMembership() {
		return this.membership;
	}

	public Program setMembership(String[] membership) {
		this.membership = membership;
		return this;
	}

	public Object getInfo() {
		return this.info;
	}

	public Program setInfo(Object info) {
		this.info = info;
		return this;
	}
}
