/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Scores associated with a FIRST team during a match at a competition
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamScore implements Serializable {

	private static final long serialVersionUID = 208364777;

	private Integer  id;
	private Integer  teamId;
	private Integer  matchId;
	private Integer  scoreTypeId;
	private String[] value;

	public TeamScore() {}

	public TeamScore(TeamScore value) {
		this.id = value.id;
		this.teamId = value.teamId;
		this.matchId = value.matchId;
		this.scoreTypeId = value.scoreTypeId;
		this.value = value.value;
	}

	public TeamScore(
		Integer  id,
		Integer  teamId,
		Integer  matchId,
		Integer  scoreTypeId,
		String[] value
	) {
		this.id = id;
		this.teamId = teamId;
		this.matchId = matchId;
		this.scoreTypeId = scoreTypeId;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public TeamScore setId(Integer id) {
		this.id = id;
		return this;
	}

	public Integer getTeamId() {
		return this.teamId;
	}

	public TeamScore setTeamId(Integer teamId) {
		this.teamId = teamId;
		return this;
	}

	public Integer getMatchId() {
		return this.matchId;
	}

	public TeamScore setMatchId(Integer matchId) {
		this.matchId = matchId;
		return this;
	}

	public Integer getScoreTypeId() {
		return this.scoreTypeId;
	}

	public TeamScore setScoreTypeId(Integer scoreTypeId) {
		this.scoreTypeId = scoreTypeId;
		return this;
	}

	public String[] getValue() {
		return this.value;
	}

	public TeamScore setValue(String[] value) {
		this.value = value;
		return this;
	}
}
