/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Sponsors associated with a FIRST team for a given game (season)
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamSponsor implements Serializable {

	private static final long serialVersionUID = 2022108381;

	private Integer id;
	private Integer teamId;
	private Integer sponsorId;
	private Integer gameId;

	public TeamSponsor() {}

	public TeamSponsor(TeamSponsor value) {
		this.id = value.id;
		this.teamId = value.teamId;
		this.sponsorId = value.sponsorId;
		this.gameId = value.gameId;
	}

	public TeamSponsor(
		Integer id,
		Integer teamId,
		Integer sponsorId,
		Integer gameId
	) {
		this.id = id;
		this.teamId = teamId;
		this.sponsorId = sponsorId;
		this.gameId = gameId;
	}

	public Integer getId() {
		return this.id;
	}

	public TeamSponsor setId(Integer id) {
		this.id = id;
		return this;
	}

	public Integer getTeamId() {
		return this.teamId;
	}

	public TeamSponsor setTeamId(Integer teamId) {
		this.teamId = teamId;
		return this;
	}

	public Integer getSponsorId() {
		return this.sponsorId;
	}

	public TeamSponsor setSponsorId(Integer sponsorId) {
		this.sponsorId = sponsorId;
		return this;
	}

	public Integer getGameId() {
		return this.gameId;
	}

	public TeamSponsor setGameId(Integer gameId) {
		this.gameId = gameId;
		return this;
	}
}
