/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Attributes associated with a FIRST team
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamAttribute implements Serializable {

	private static final long serialVersionUID = 92553843;

	private Integer id;
	private Integer teamId;
	private Object  attributes;

	public TeamAttribute() {}

	public TeamAttribute(TeamAttribute value) {
		this.id = value.id;
		this.teamId = value.teamId;
		this.attributes = value.attributes;
	}

	public TeamAttribute(
		Integer id,
		Integer teamId,
		Object  attributes
	) {
		this.id = id;
		this.teamId = teamId;
		this.attributes = attributes;
	}

	public Integer getId() {
		return this.id;
	}

	public TeamAttribute setId(Integer id) {
		this.id = id;
		return this;
	}

	public Integer getTeamId() {
		return this.teamId;
	}

	public TeamAttribute setTeamId(Integer teamId) {
		this.teamId = teamId;
		return this;
	}

	public Object getAttributes() {
		return this.attributes;
	}

	public TeamAttribute setAttributes(Object attributes) {
		this.attributes = attributes;
		return this;
	}
}
