/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.technojays.first.jooq.tables.AllianceType;


/**
 * Alliance types for FIRST programs
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllianceTypeRecord extends UpdatableRecordImpl<AllianceTypeRecord> implements Record3<Integer, String, String[]> {

	private static final long serialVersionUID = 1081452329;

	/**
	 * Setter for <code>first.alliance_type.id</code>. System id for alliance type
	 */
	public AllianceTypeRecord setId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>first.alliance_type.id</code>. System id for alliance type
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>first.alliance_type.name</code>. Name for alliance type
	 */
	public AllianceTypeRecord setName(String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>first.alliance_type.name</code>. Name for alliance type
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>first.alliance_type.short_name</code>. Short Name for alliance type
	 */
	public AllianceTypeRecord setShortName(String[] value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>first.alliance_type.short_name</code>. Short Name for alliance type
	 */
	public String[] getShortName() {
		return (String[]) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String[]> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String[]> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return AllianceType.ALLIANCE_TYPE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return AllianceType.ALLIANCE_TYPE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String[]> field3() {
		return AllianceType.ALLIANCE_TYPE.SHORT_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String[] value3() {
		return getShortName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AllianceTypeRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AllianceTypeRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AllianceTypeRecord value3(String[] value) {
		setShortName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AllianceTypeRecord values(Integer value1, String value2, String[] value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AllianceTypeRecord
	 */
	public AllianceTypeRecord() {
		super(AllianceType.ALLIANCE_TYPE);
	}

	/**
	 * Create a detached, initialised AllianceTypeRecord
	 */
	public AllianceTypeRecord(Integer id, String name, String[] shortName) {
		super(AllianceType.ALLIANCE_TYPE);

		setValue(0, id);
		setValue(1, name);
		setValue(2, shortName);
	}
}
