/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.technojays.first.jooq.tables.Ally;


/**
 * Relationship between a set of teams for an alliance
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllyRecord extends UpdatableRecordImpl<AllyRecord> implements Record3<Integer, Integer, String[]> {

	private static final long serialVersionUID = 944603438;

	/**
	 * Setter for <code>first.ally.id</code>.
	 */
	public AllyRecord setId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>first.ally.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>first.ally.team_id</code>.
	 */
	public AllyRecord setTeamId(Integer value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>first.ally.team_id</code>.
	 */
	public Integer getTeamId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>first.ally.ally_ref</code>.
	 */
	public AllyRecord setAllyRef(String[] value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>first.ally.ally_ref</code>.
	 */
	public String[] getAllyRef() {
		return (String[]) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, String[]> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, String[]> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Ally.ALLY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Ally.ALLY.TEAM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String[]> field3() {
		return Ally.ALLY.ALLY_REF;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getTeamId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String[] value3() {
		return getAllyRef();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AllyRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AllyRecord value2(Integer value) {
		setTeamId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AllyRecord value3(String[] value) {
		setAllyRef(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AllyRecord values(Integer value1, Integer value2, String[] value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AllyRecord
	 */
	public AllyRecord() {
		super(Ally.ALLY);
	}

	/**
	 * Create a detached, initialised AllyRecord
	 */
	public AllyRecord(Integer id, Integer teamId, String[] allyRef) {
		super(Ally.ALLY);

		setValue(0, id);
		setValue(1, teamId);
		setValue(2, allyRef);
	}
}
