/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.technojays.first.jooq.tables.AttributeType;


/**
 * Attribute types in program
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AttributeTypeRecord extends UpdatableRecordImpl<AttributeTypeRecord> implements Record2<Integer, Object> {

	private static final long serialVersionUID = 2117937831;

	/**
	 * Setter for <code>first.attribute_type.id</code>. system id for this attribute type
	 */
	public AttributeTypeRecord setId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>first.attribute_type.id</code>. system id for this attribute type
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>first.attribute_type.info</code>. info for this attribute type
	 */
	public AttributeTypeRecord setInfo(Object value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>first.attribute_type.info</code>. info for this attribute type
	 */
	public Object getInfo() {
		return (Object) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Object> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Object> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return AttributeType.ATTRIBUTE_TYPE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Object> field2() {
		return AttributeType.ATTRIBUTE_TYPE.INFO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Object value2() {
		return getInfo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttributeTypeRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttributeTypeRecord value2(Object value) {
		setInfo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttributeTypeRecord values(Integer value1, Object value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AttributeTypeRecord
	 */
	public AttributeTypeRecord() {
		super(AttributeType.ATTRIBUTE_TYPE);
	}

	/**
	 * Create a detached, initialised AttributeTypeRecord
	 */
	public AttributeTypeRecord(Integer id, Object info) {
		super(AttributeType.ATTRIBUTE_TYPE);

		setValue(0, id);
		setValue(1, info);
	}
}
