/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.technojays.first.jooq.tables.Competition;


/**
 * A competition describes a Location, Game, and is held at an Event
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompetitionRecord extends UpdatableRecordImpl<CompetitionRecord> implements Record6<Integer, String, Integer, Integer, Integer, Integer> {

	private static final long serialVersionUID = 895655415;

	/**
	 * Setter for <code>first.competition.id</code>.
	 */
	public CompetitionRecord setId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>first.competition.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>first.competition.name</code>.
	 */
	public CompetitionRecord setName(String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>first.competition.name</code>.
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>first.competition.type_id</code>. comptetion type id
	 */
	public CompetitionRecord setTypeId(Integer value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>first.competition.type_id</code>. comptetion type id
	 */
	public Integer getTypeId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>first.competition.event_id</code>.
	 */
	public CompetitionRecord setEventId(Integer value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>first.competition.event_id</code>.
	 */
	public Integer getEventId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>first.competition.location_id</code>.
	 */
	public CompetitionRecord setLocationId(Integer value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>first.competition.location_id</code>.
	 */
	public Integer getLocationId() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>first.competition.game_id</code>.
	 */
	public CompetitionRecord setGameId(Integer value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>first.competition.game_id</code>.
	 */
	public Integer getGameId() {
		return (Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, Integer, Integer, Integer, Integer> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, Integer, Integer, Integer, Integer> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Competition.COMPETITION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Competition.COMPETITION.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Competition.COMPETITION.TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Competition.COMPETITION.EVENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Competition.COMPETITION.LOCATION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Competition.COMPETITION.GAME_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getEventId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getLocationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getGameId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompetitionRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompetitionRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompetitionRecord value3(Integer value) {
		setTypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompetitionRecord value4(Integer value) {
		setEventId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompetitionRecord value5(Integer value) {
		setLocationId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompetitionRecord value6(Integer value) {
		setGameId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompetitionRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5, Integer value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CompetitionRecord
	 */
	public CompetitionRecord() {
		super(Competition.COMPETITION);
	}

	/**
	 * Create a detached, initialised CompetitionRecord
	 */
	public CompetitionRecord(Integer id, String name, Integer typeId, Integer eventId, Integer locationId, Integer gameId) {
		super(Competition.COMPETITION);

		setValue(0, id);
		setValue(1, name);
		setValue(2, typeId);
		setValue(3, eventId);
		setValue(4, locationId);
		setValue(5, gameId);
	}
}
