/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.technojays.first.jooq.tables.Event;


/**
 * An event describes the timeframe for competitions and celebrations that 
 * are managed together
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventRecord extends UpdatableRecordImpl<EventRecord> implements Record6<Integer, String, String[], Timestamp, Timestamp, Object> {

	private static final long serialVersionUID = -82734242;

	/**
	 * Setter for <code>first.event.id</code>. event system id
	 */
	public EventRecord setId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>first.event.id</code>. event system id
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>first.event.name</code>. display name for event
	 */
	public EventRecord setName(String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>first.event.name</code>. display name for event
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>first.event.short_name</code>. Short name for event
	 */
	public EventRecord setShortName(String[] value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>first.event.short_name</code>. Short name for event
	 */
	public String[] getShortName() {
		return (String[]) getValue(2);
	}

	/**
	 * Setter for <code>first.event.start_date</code>. start date of event
	 */
	public EventRecord setStartDate(Timestamp value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>first.event.start_date</code>. start date of event
	 */
	public Timestamp getStartDate() {
		return (Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>first.event.end_date</code>. end date of event
	 */
	public EventRecord setEndDate(Timestamp value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>first.event.end_date</code>. end date of event
	 */
	public Timestamp getEndDate() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>first.event.info</code>. event info
	 */
	public EventRecord setInfo(Object value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>first.event.info</code>. event info
	 */
	public Object getInfo() {
		return (Object) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, String[], Timestamp, Timestamp, Object> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, String[], Timestamp, Timestamp, Object> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Event.EVENT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Event.EVENT.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String[]> field3() {
		return Event.EVENT.SHORT_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return Event.EVENT.START_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return Event.EVENT.END_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Object> field6() {
		return Event.EVENT.INFO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String[] value3() {
		return getShortName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getStartDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getEndDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Object value6() {
		return getInfo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventRecord value3(String[] value) {
		setShortName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventRecord value4(Timestamp value) {
		setStartDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventRecord value5(Timestamp value) {
		setEndDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventRecord value6(Object value) {
		setInfo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventRecord values(Integer value1, String value2, String[] value3, Timestamp value4, Timestamp value5, Object value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EventRecord
	 */
	public EventRecord() {
		super(Event.EVENT);
	}

	/**
	 * Create a detached, initialised EventRecord
	 */
	public EventRecord(Integer id, String name, String[] shortName, Timestamp startDate, Timestamp endDate, Object info) {
		super(Event.EVENT);

		setValue(0, id);
		setValue(1, name);
		setValue(2, shortName);
		setValue(3, startDate);
		setValue(4, endDate);
		setValue(5, info);
	}
}
