/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.technojays.first.jooq.tables.Game;


/**
 * A game describes a specific set of rules and competitions for a program 
 * and its teams. It has a period of time 
 * associated with it.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameRecord extends UpdatableRecordImpl<GameRecord> implements Record6<Integer, String, String[], Integer, Timestamp, Timestamp> {

	private static final long serialVersionUID = -461219800;

	/**
	 * Setter for <code>first.game.id</code>.
	 */
	public GameRecord setId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>first.game.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>first.game.name</code>.
	 */
	public GameRecord setName(String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>first.game.name</code>.
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>first.game.short_name</code>.
	 */
	public GameRecord setShortName(String[] value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>first.game.short_name</code>.
	 */
	public String[] getShortName() {
		return (String[]) getValue(2);
	}

	/**
	 * Setter for <code>first.game.program_id</code>. system id of associated program
	 */
	public GameRecord setProgramId(Integer value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>first.game.program_id</code>. system id of associated program
	 */
	public Integer getProgramId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>first.game.start_date</code>. Game start date
	 */
	public GameRecord setStartDate(Timestamp value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>first.game.start_date</code>. Game start date
	 */
	public Timestamp getStartDate() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>first.game.end_date</code>. end date of season
	 */
	public GameRecord setEndDate(Timestamp value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>first.game.end_date</code>. end date of season
	 */
	public Timestamp getEndDate() {
		return (Timestamp) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, String[], Integer, Timestamp, Timestamp> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, String[], Integer, Timestamp, Timestamp> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Game.GAME.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Game.GAME.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String[]> field3() {
		return Game.GAME.SHORT_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Game.GAME.PROGRAM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return Game.GAME.START_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return Game.GAME.END_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String[] value3() {
		return getShortName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getProgramId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getStartDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getEndDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameRecord value3(String[] value) {
		setShortName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameRecord value4(Integer value) {
		setProgramId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameRecord value5(Timestamp value) {
		setStartDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameRecord value6(Timestamp value) {
		setEndDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameRecord values(Integer value1, String value2, String[] value3, Integer value4, Timestamp value5, Timestamp value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GameRecord
	 */
	public GameRecord() {
		super(Game.GAME);
	}

	/**
	 * Create a detached, initialised GameRecord
	 */
	public GameRecord(Integer id, String name, String[] shortName, Integer programId, Timestamp startDate, Timestamp endDate) {
		super(Game.GAME);

		setValue(0, id);
		setValue(1, name);
		setValue(2, shortName);
		setValue(3, programId);
		setValue(4, startDate);
		setValue(5, endDate);
	}
}
