/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.technojays.first.jooq.tables.Location;


/**
 * Locations for program
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LocationRecord extends UpdatableRecordImpl<LocationRecord> implements Record4<Integer, Double, Double, Integer> {

	private static final long serialVersionUID = -64457835;

	/**
	 * Setter for <code>first.location.id</code>. location system id
	 */
	public LocationRecord setId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>first.location.id</code>. location system id
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>first.location.lng</code>.
	 */
	public LocationRecord setLng(Double value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>first.location.lng</code>.
	 */
	public Double getLng() {
		return (Double) getValue(1);
	}

	/**
	 * Setter for <code>first.location.lat</code>.
	 */
	public LocationRecord setLat(Double value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>first.location.lat</code>.
	 */
	public Double getLat() {
		return (Double) getValue(2);
	}

	/**
	 * Setter for <code>first.location.place_id</code>.
	 */
	public LocationRecord setPlaceId(Integer value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>first.location.place_id</code>.
	 */
	public Integer getPlaceId() {
		return (Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Double, Double, Integer> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Double, Double, Integer> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Location.LOCATION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field2() {
		return Location.LOCATION.LNG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field3() {
		return Location.LOCATION.LAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Location.LOCATION.PLACE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value2() {
		return getLng();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value3() {
		return getLat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getPlaceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LocationRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LocationRecord value2(Double value) {
		setLng(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LocationRecord value3(Double value) {
		setLat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LocationRecord value4(Integer value) {
		setPlaceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LocationRecord values(Integer value1, Double value2, Double value3, Integer value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LocationRecord
	 */
	public LocationRecord() {
		super(Location.LOCATION);
	}

	/**
	 * Create a detached, initialised LocationRecord
	 */
	public LocationRecord(Integer id, Double lng, Double lat, Integer placeId) {
		super(Location.LOCATION);

		setValue(0, id);
		setValue(1, lng);
		setValue(2, lat);
		setValue(3, placeId);
	}
}
