/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.technojays.first.jooq.tables.AllianceType;
import org.technojays.first.jooq.tables.records.AllianceTypeRecord;


/**
 * Alliance types for FIRST programs
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllianceTypeDao extends DAOImpl<AllianceTypeRecord, org.technojays.first.jooq.tables.pojos.AllianceType, Integer> {

	/**
	 * Create a new AllianceTypeDao without any configuration
	 */
	public AllianceTypeDao() {
		super(AllianceType.ALLIANCE_TYPE, org.technojays.first.jooq.tables.pojos.AllianceType.class);
	}

	/**
	 * Create a new AllianceTypeDao with an attached configuration
	 */
	public AllianceTypeDao(Configuration configuration) {
		super(AllianceType.ALLIANCE_TYPE, org.technojays.first.jooq.tables.pojos.AllianceType.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.technojays.first.jooq.tables.pojos.AllianceType object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.AllianceType> fetchById(Integer... values) {
		return fetch(AllianceType.ALLIANCE_TYPE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.technojays.first.jooq.tables.pojos.AllianceType fetchOneById(Integer value) {
		return fetchOne(AllianceType.ALLIANCE_TYPE.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.AllianceType> fetchByName(String... values) {
		return fetch(AllianceType.ALLIANCE_TYPE.NAME, values);
	}

	/**
	 * Fetch records that have <code>short_name IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.AllianceType> fetchByShortName(String[]... values) {
		return fetch(AllianceType.ALLIANCE_TYPE.SHORT_NAME, values);
	}

	/**
	 * Fetch a unique record that has <code>short_name = value</code>
	 */
	public org.technojays.first.jooq.tables.pojos.AllianceType fetchOneByShortName(String[] value) {
		return fetchOne(AllianceType.ALLIANCE_TYPE.SHORT_NAME, value);
	}
}
