/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.technojays.first.jooq.tables.Alliance;
import org.technojays.first.jooq.tables.records.AllianceRecord;


/**
 * Relationship between a match and a group of allies
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllianceDao extends DAOImpl<AllianceRecord, org.technojays.first.jooq.tables.pojos.Alliance, Integer> {

	/**
	 * Create a new AllianceDao without any configuration
	 */
	public AllianceDao() {
		super(Alliance.ALLIANCE, org.technojays.first.jooq.tables.pojos.Alliance.class);
	}

	/**
	 * Create a new AllianceDao with an attached configuration
	 */
	public AllianceDao(Configuration configuration) {
		super(Alliance.ALLIANCE, org.technojays.first.jooq.tables.pojos.Alliance.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.technojays.first.jooq.tables.pojos.Alliance object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Alliance> fetchById(Integer... values) {
		return fetch(Alliance.ALLIANCE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.technojays.first.jooq.tables.pojos.Alliance fetchOneById(Integer value) {
		return fetchOne(Alliance.ALLIANCE.ID, value);
	}

	/**
	 * Fetch records that have <code>type IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Alliance> fetchByType(Integer... values) {
		return fetch(Alliance.ALLIANCE.TYPE, values);
	}

	/**
	 * Fetch records that have <code>match_id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Alliance> fetchByMatchId(Integer... values) {
		return fetch(Alliance.ALLIANCE.MATCH_ID, values);
	}

	/**
	 * Fetch records that have <code>ally_ref IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Alliance> fetchByAllyRef(String... values) {
		return fetch(Alliance.ALLIANCE.ALLY_REF, values);
	}
}
