/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.technojays.first.jooq.tables.Ally;
import org.technojays.first.jooq.tables.records.AllyRecord;


/**
 * Relationship between a set of teams for an alliance
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllyDao extends DAOImpl<AllyRecord, org.technojays.first.jooq.tables.pojos.Ally, Integer> {

	/**
	 * Create a new AllyDao without any configuration
	 */
	public AllyDao() {
		super(Ally.ALLY, org.technojays.first.jooq.tables.pojos.Ally.class);
	}

	/**
	 * Create a new AllyDao with an attached configuration
	 */
	public AllyDao(Configuration configuration) {
		super(Ally.ALLY, org.technojays.first.jooq.tables.pojos.Ally.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.technojays.first.jooq.tables.pojos.Ally object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Ally> fetchById(Integer... values) {
		return fetch(Ally.ALLY.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.technojays.first.jooq.tables.pojos.Ally fetchOneById(Integer value) {
		return fetchOne(Ally.ALLY.ID, value);
	}

	/**
	 * Fetch records that have <code>team_id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Ally> fetchByTeamId(Integer... values) {
		return fetch(Ally.ALLY.TEAM_ID, values);
	}

	/**
	 * Fetch records that have <code>ally_ref IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Ally> fetchByAllyRef(String[]... values) {
		return fetch(Ally.ALLY.ALLY_REF, values);
	}
}
