/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.technojays.first.jooq.tables.Award;
import org.technojays.first.jooq.tables.records.AwardRecord;


/**
 * Awards awarded at competitions and events
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AwardDao extends DAOImpl<AwardRecord, org.technojays.first.jooq.tables.pojos.Award, Integer> {

	/**
	 * Create a new AwardDao without any configuration
	 */
	public AwardDao() {
		super(Award.AWARD, org.technojays.first.jooq.tables.pojos.Award.class);
	}

	/**
	 * Create a new AwardDao with an attached configuration
	 */
	public AwardDao(Configuration configuration) {
		super(Award.AWARD, org.technojays.first.jooq.tables.pojos.Award.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.technojays.first.jooq.tables.pojos.Award object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Award> fetchById(Integer... values) {
		return fetch(Award.AWARD.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.technojays.first.jooq.tables.pojos.Award fetchOneById(Integer value) {
		return fetchOne(Award.AWARD.ID, value);
	}

	/**
	 * Fetch records that have <code>type_id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Award> fetchByTypeId(Integer... values) {
		return fetch(Award.AWARD.TYPE_ID, values);
	}

	/**
	 * Fetch records that have <code>event_id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Award> fetchByEventId(Integer... values) {
		return fetch(Award.AWARD.EVENT_ID, values);
	}

	/**
	 * Fetch records that have <code>competition_id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Award> fetchByCompetitionId(Integer... values) {
		return fetch(Award.AWARD.COMPETITION_ID, values);
	}

	/**
	 * Fetch records that have <code>team_id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Award> fetchByTeamId(Integer... values) {
		return fetch(Award.AWARD.TEAM_ID, values);
	}

	/**
	 * Fetch records that have <code>awardee_id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Award> fetchByAwardeeId(Integer... values) {
		return fetch(Award.AWARD.AWARDEE_ID, values);
	}
}
