/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.technojays.first.jooq.tables.Event;
import org.technojays.first.jooq.tables.records.EventRecord;


/**
 * An event describes the timeframe for competitions and celebrations that 
 * are managed together
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventDao extends DAOImpl<EventRecord, org.technojays.first.jooq.tables.pojos.Event, Integer> {

	/**
	 * Create a new EventDao without any configuration
	 */
	public EventDao() {
		super(Event.EVENT, org.technojays.first.jooq.tables.pojos.Event.class);
	}

	/**
	 * Create a new EventDao with an attached configuration
	 */
	public EventDao(Configuration configuration) {
		super(Event.EVENT, org.technojays.first.jooq.tables.pojos.Event.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.technojays.first.jooq.tables.pojos.Event object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Event> fetchById(Integer... values) {
		return fetch(Event.EVENT.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.technojays.first.jooq.tables.pojos.Event fetchOneById(Integer value) {
		return fetchOne(Event.EVENT.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Event> fetchByName(String... values) {
		return fetch(Event.EVENT.NAME, values);
	}

	/**
	 * Fetch records that have <code>short_name IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Event> fetchByShortName(String[]... values) {
		return fetch(Event.EVENT.SHORT_NAME, values);
	}

	/**
	 * Fetch a unique record that has <code>short_name = value</code>
	 */
	public org.technojays.first.jooq.tables.pojos.Event fetchOneByShortName(String[] value) {
		return fetchOne(Event.EVENT.SHORT_NAME, value);
	}

	/**
	 * Fetch records that have <code>start_date IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Event> fetchByStartDate(Timestamp... values) {
		return fetch(Event.EVENT.START_DATE, values);
	}

	/**
	 * Fetch records that have <code>end_date IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Event> fetchByEndDate(Timestamp... values) {
		return fetch(Event.EVENT.END_DATE, values);
	}

	/**
	 * Fetch records that have <code>info IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Event> fetchByInfo(Object... values) {
		return fetch(Event.EVENT.INFO, values);
	}
}
