/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.technojays.first.jooq.tables.Game;
import org.technojays.first.jooq.tables.records.GameRecord;


/**
 * A game describes a specific set of rules and competitions for a program 
 * and its teams. It has a period of time 
 * associated with it.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameDao extends DAOImpl<GameRecord, org.technojays.first.jooq.tables.pojos.Game, Integer> {

	/**
	 * Create a new GameDao without any configuration
	 */
	public GameDao() {
		super(Game.GAME, org.technojays.first.jooq.tables.pojos.Game.class);
	}

	/**
	 * Create a new GameDao with an attached configuration
	 */
	public GameDao(Configuration configuration) {
		super(Game.GAME, org.technojays.first.jooq.tables.pojos.Game.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.technojays.first.jooq.tables.pojos.Game object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Game> fetchById(Integer... values) {
		return fetch(Game.GAME.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.technojays.first.jooq.tables.pojos.Game fetchOneById(Integer value) {
		return fetchOne(Game.GAME.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Game> fetchByName(String... values) {
		return fetch(Game.GAME.NAME, values);
	}

	/**
	 * Fetch records that have <code>short_name IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Game> fetchByShortName(String[]... values) {
		return fetch(Game.GAME.SHORT_NAME, values);
	}

	/**
	 * Fetch a unique record that has <code>short_name = value</code>
	 */
	public org.technojays.first.jooq.tables.pojos.Game fetchOneByShortName(String[] value) {
		return fetchOne(Game.GAME.SHORT_NAME, value);
	}

	/**
	 * Fetch records that have <code>program_id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Game> fetchByProgramId(Integer... values) {
		return fetch(Game.GAME.PROGRAM_ID, values);
	}

	/**
	 * Fetch records that have <code>start_date IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Game> fetchByStartDate(Timestamp... values) {
		return fetch(Game.GAME.START_DATE, values);
	}

	/**
	 * Fetch records that have <code>end_date IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Game> fetchByEndDate(Timestamp... values) {
		return fetch(Game.GAME.END_DATE, values);
	}
}
