/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.technojays.first.jooq.tables.Location;
import org.technojays.first.jooq.tables.records.LocationRecord;


/**
 * Locations for program
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LocationDao extends DAOImpl<LocationRecord, org.technojays.first.jooq.tables.pojos.Location, Integer> {

	/**
	 * Create a new LocationDao without any configuration
	 */
	public LocationDao() {
		super(Location.LOCATION, org.technojays.first.jooq.tables.pojos.Location.class);
	}

	/**
	 * Create a new LocationDao with an attached configuration
	 */
	public LocationDao(Configuration configuration) {
		super(Location.LOCATION, org.technojays.first.jooq.tables.pojos.Location.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.technojays.first.jooq.tables.pojos.Location object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Location> fetchById(Integer... values) {
		return fetch(Location.LOCATION.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.technojays.first.jooq.tables.pojos.Location fetchOneById(Integer value) {
		return fetchOne(Location.LOCATION.ID, value);
	}

	/**
	 * Fetch records that have <code>lng IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Location> fetchByLng(Double... values) {
		return fetch(Location.LOCATION.LNG, values);
	}

	/**
	 * Fetch records that have <code>lat IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Location> fetchByLat(Double... values) {
		return fetch(Location.LOCATION.LAT, values);
	}

	/**
	 * Fetch records that have <code>place_id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Location> fetchByPlaceId(Integer... values) {
		return fetch(Location.LOCATION.PLACE_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>place_id = value</code>
	 */
	public org.technojays.first.jooq.tables.pojos.Location fetchOneByPlaceId(Integer value) {
		return fetchOne(Location.LOCATION.PLACE_ID, value);
	}
}
