/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.technojays.first.jooq.tables.MatchScore;
import org.technojays.first.jooq.tables.records.MatchScoreRecord;


/**
 * Scores associated with a match
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MatchScoreDao extends DAOImpl<MatchScoreRecord, org.technojays.first.jooq.tables.pojos.MatchScore, Integer> {

	/**
	 * Create a new MatchScoreDao without any configuration
	 */
	public MatchScoreDao() {
		super(MatchScore.MATCH_SCORE, org.technojays.first.jooq.tables.pojos.MatchScore.class);
	}

	/**
	 * Create a new MatchScoreDao with an attached configuration
	 */
	public MatchScoreDao(Configuration configuration) {
		super(MatchScore.MATCH_SCORE, org.technojays.first.jooq.tables.pojos.MatchScore.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.technojays.first.jooq.tables.pojos.MatchScore object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.MatchScore> fetchById(Integer... values) {
		return fetch(MatchScore.MATCH_SCORE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.technojays.first.jooq.tables.pojos.MatchScore fetchOneById(Integer value) {
		return fetchOne(MatchScore.MATCH_SCORE.ID, value);
	}

	/**
	 * Fetch records that have <code>match_id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.MatchScore> fetchByMatchId(Integer... values) {
		return fetch(MatchScore.MATCH_SCORE.MATCH_ID, values);
	}

	/**
	 * Fetch records that have <code>alliance_id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.MatchScore> fetchByAllianceId(Integer... values) {
		return fetch(MatchScore.MATCH_SCORE.ALLIANCE_ID, values);
	}

	/**
	 * Fetch records that have <code>score_type_id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.MatchScore> fetchByScoreTypeId(Integer... values) {
		return fetch(MatchScore.MATCH_SCORE.SCORE_TYPE_ID, values);
	}

	/**
	 * Fetch records that have <code>value IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.MatchScore> fetchByValue(String[]... values) {
		return fetch(MatchScore.MATCH_SCORE.VALUE, values);
	}
}
