/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.technojays.first.jooq.tables.Program;
import org.technojays.first.jooq.tables.records.ProgramRecord;


/**
 * A program is a sub-organization of FIRST that describes the type of games 
 * that will be played and the 
 * types of participants.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProgramDao extends DAOImpl<ProgramRecord, org.technojays.first.jooq.tables.pojos.Program, Integer> {

	/**
	 * Create a new ProgramDao without any configuration
	 */
	public ProgramDao() {
		super(Program.PROGRAM, org.technojays.first.jooq.tables.pojos.Program.class);
	}

	/**
	 * Create a new ProgramDao with an attached configuration
	 */
	public ProgramDao(Configuration configuration) {
		super(Program.PROGRAM, org.technojays.first.jooq.tables.pojos.Program.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.technojays.first.jooq.tables.pojos.Program object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Program> fetchById(Integer... values) {
		return fetch(Program.PROGRAM.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.technojays.first.jooq.tables.pojos.Program fetchOneById(Integer value) {
		return fetchOne(Program.PROGRAM.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Program> fetchByName(String... values) {
		return fetch(Program.PROGRAM.NAME, values);
	}

	/**
	 * Fetch records that have <code>short_name IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Program> fetchByShortName(String[]... values) {
		return fetch(Program.PROGRAM.SHORT_NAME, values);
	}

	/**
	 * Fetch a unique record that has <code>short_name = value</code>
	 */
	public org.technojays.first.jooq.tables.pojos.Program fetchOneByShortName(String[] value) {
		return fetchOne(Program.PROGRAM.SHORT_NAME, value);
	}

	/**
	 * Fetch records that have <code>membership IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Program> fetchByMembership(String[]... values) {
		return fetch(Program.PROGRAM.MEMBERSHIP, values);
	}

	/**
	 * Fetch records that have <code>info IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Program> fetchByInfo(Object... values) {
		return fetch(Program.PROGRAM.INFO, values);
	}
}
