/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.technojays.first.jooq.tables.ScoreType;
import org.technojays.first.jooq.tables.records.ScoreTypeRecord;


/**
 * Types of scores associated with matches
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScoreTypeDao extends DAOImpl<ScoreTypeRecord, org.technojays.first.jooq.tables.pojos.ScoreType, Integer> {

	/**
	 * Create a new ScoreTypeDao without any configuration
	 */
	public ScoreTypeDao() {
		super(ScoreType.SCORE_TYPE, org.technojays.first.jooq.tables.pojos.ScoreType.class);
	}

	/**
	 * Create a new ScoreTypeDao with an attached configuration
	 */
	public ScoreTypeDao(Configuration configuration) {
		super(ScoreType.SCORE_TYPE, org.technojays.first.jooq.tables.pojos.ScoreType.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.technojays.first.jooq.tables.pojos.ScoreType object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.ScoreType> fetchById(Integer... values) {
		return fetch(ScoreType.SCORE_TYPE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.technojays.first.jooq.tables.pojos.ScoreType fetchOneById(Integer value) {
		return fetchOne(ScoreType.SCORE_TYPE.ID, value);
	}

	/**
	 * Fetch records that have <code>info IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.ScoreType> fetchByInfo(Object... values) {
		return fetch(ScoreType.SCORE_TYPE.INFO, values);
	}
}
