/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.technojays.first.jooq.tables.Sponsor;
import org.technojays.first.jooq.tables.records.SponsorRecord;


/**
 * Sponsors for teams, events, groups, programs, etc
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SponsorDao extends DAOImpl<SponsorRecord, org.technojays.first.jooq.tables.pojos.Sponsor, Integer> {

	/**
	 * Create a new SponsorDao without any configuration
	 */
	public SponsorDao() {
		super(Sponsor.SPONSOR, org.technojays.first.jooq.tables.pojos.Sponsor.class);
	}

	/**
	 * Create a new SponsorDao with an attached configuration
	 */
	public SponsorDao(Configuration configuration) {
		super(Sponsor.SPONSOR, org.technojays.first.jooq.tables.pojos.Sponsor.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.technojays.first.jooq.tables.pojos.Sponsor object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Sponsor> fetchById(Integer... values) {
		return fetch(Sponsor.SPONSOR.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.technojays.first.jooq.tables.pojos.Sponsor fetchOneById(Integer value) {
		return fetchOne(Sponsor.SPONSOR.ID, value);
	}

	/**
	 * Fetch records that have <code>info IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.Sponsor> fetchByInfo(Object... values) {
		return fetch(Sponsor.SPONSOR.INFO, values);
	}
}
