/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.technojays.first.jooq.tables.TeamAttribute;
import org.technojays.first.jooq.tables.records.TeamAttributeRecord;


/**
 * Attributes associated with a FIRST team
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamAttributeDao extends DAOImpl<TeamAttributeRecord, org.technojays.first.jooq.tables.pojos.TeamAttribute, Integer> {

	/**
	 * Create a new TeamAttributeDao without any configuration
	 */
	public TeamAttributeDao() {
		super(TeamAttribute.TEAM_ATTRIBUTE, org.technojays.first.jooq.tables.pojos.TeamAttribute.class);
	}

	/**
	 * Create a new TeamAttributeDao with an attached configuration
	 */
	public TeamAttributeDao(Configuration configuration) {
		super(TeamAttribute.TEAM_ATTRIBUTE, org.technojays.first.jooq.tables.pojos.TeamAttribute.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.technojays.first.jooq.tables.pojos.TeamAttribute object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.TeamAttribute> fetchById(Integer... values) {
		return fetch(TeamAttribute.TEAM_ATTRIBUTE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.technojays.first.jooq.tables.pojos.TeamAttribute fetchOneById(Integer value) {
		return fetchOne(TeamAttribute.TEAM_ATTRIBUTE.ID, value);
	}

	/**
	 * Fetch records that have <code>team_id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.TeamAttribute> fetchByTeamId(Integer... values) {
		return fetch(TeamAttribute.TEAM_ATTRIBUTE.TEAM_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>team_id = value</code>
	 */
	public org.technojays.first.jooq.tables.pojos.TeamAttribute fetchOneByTeamId(Integer value) {
		return fetchOne(TeamAttribute.TEAM_ATTRIBUTE.TEAM_ID, value);
	}

	/**
	 * Fetch records that have <code>attributes IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.TeamAttribute> fetchByAttributes(Object... values) {
		return fetch(TeamAttribute.TEAM_ATTRIBUTE.ATTRIBUTES, values);
	}
}
