/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.technojays.first.jooq.tables.TeamScore;
import org.technojays.first.jooq.tables.records.TeamScoreRecord;


/**
 * Scores associated with a FIRST team during a match at a competition
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamScoreDao extends DAOImpl<TeamScoreRecord, org.technojays.first.jooq.tables.pojos.TeamScore, Integer> {

	/**
	 * Create a new TeamScoreDao without any configuration
	 */
	public TeamScoreDao() {
		super(TeamScore.TEAM_SCORE, org.technojays.first.jooq.tables.pojos.TeamScore.class);
	}

	/**
	 * Create a new TeamScoreDao with an attached configuration
	 */
	public TeamScoreDao(Configuration configuration) {
		super(TeamScore.TEAM_SCORE, org.technojays.first.jooq.tables.pojos.TeamScore.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.technojays.first.jooq.tables.pojos.TeamScore object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.TeamScore> fetchById(Integer... values) {
		return fetch(TeamScore.TEAM_SCORE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.technojays.first.jooq.tables.pojos.TeamScore fetchOneById(Integer value) {
		return fetchOne(TeamScore.TEAM_SCORE.ID, value);
	}

	/**
	 * Fetch records that have <code>team_id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.TeamScore> fetchByTeamId(Integer... values) {
		return fetch(TeamScore.TEAM_SCORE.TEAM_ID, values);
	}

	/**
	 * Fetch records that have <code>match_id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.TeamScore> fetchByMatchId(Integer... values) {
		return fetch(TeamScore.TEAM_SCORE.MATCH_ID, values);
	}

	/**
	 * Fetch records that have <code>score_type_id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.TeamScore> fetchByScoreTypeId(Integer... values) {
		return fetch(TeamScore.TEAM_SCORE.SCORE_TYPE_ID, values);
	}

	/**
	 * Fetch records that have <code>value IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.TeamScore> fetchByValue(String[]... values) {
		return fetch(TeamScore.TEAM_SCORE.VALUE, values);
	}
}
