/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.technojays.first.jooq.tables.TeamSponsor;
import org.technojays.first.jooq.tables.records.TeamSponsorRecord;


/**
 * Sponsors associated with a FIRST team for a given game (season)
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamSponsorDao extends DAOImpl<TeamSponsorRecord, org.technojays.first.jooq.tables.pojos.TeamSponsor, Integer> {

	/**
	 * Create a new TeamSponsorDao without any configuration
	 */
	public TeamSponsorDao() {
		super(TeamSponsor.TEAM_SPONSOR, org.technojays.first.jooq.tables.pojos.TeamSponsor.class);
	}

	/**
	 * Create a new TeamSponsorDao with an attached configuration
	 */
	public TeamSponsorDao(Configuration configuration) {
		super(TeamSponsor.TEAM_SPONSOR, org.technojays.first.jooq.tables.pojos.TeamSponsor.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.technojays.first.jooq.tables.pojos.TeamSponsor object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.TeamSponsor> fetchById(Integer... values) {
		return fetch(TeamSponsor.TEAM_SPONSOR.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.technojays.first.jooq.tables.pojos.TeamSponsor fetchOneById(Integer value) {
		return fetchOne(TeamSponsor.TEAM_SPONSOR.ID, value);
	}

	/**
	 * Fetch records that have <code>team_id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.TeamSponsor> fetchByTeamId(Integer... values) {
		return fetch(TeamSponsor.TEAM_SPONSOR.TEAM_ID, values);
	}

	/**
	 * Fetch records that have <code>sponsor_id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.TeamSponsor> fetchBySponsorId(Integer... values) {
		return fetch(TeamSponsor.TEAM_SPONSOR.SPONSOR_ID, values);
	}

	/**
	 * Fetch records that have <code>game_id IN (values)</code>
	 */
	public List<org.technojays.first.jooq.tables.pojos.TeamSponsor> fetchByGameId(Integer... values) {
		return fetch(TeamSponsor.TEAM_SPONSOR.GAME_ID, values);
	}
}
