/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.technojays.first.jooq.First;
import org.technojays.first.jooq.Keys;
import org.technojays.first.jooq.tables.records.ProgramRecord;


/**
 * A program is a sub-organization of FIRST that describes the type of games 
 * that will be played and the 
 * types of participants.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Program extends TableImpl<ProgramRecord> {

	private static final long serialVersionUID = 148070676;

	/**
	 * The reference instance of <code>first.program</code>
	 */
	public static final Program PROGRAM = new Program();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ProgramRecord> getRecordType() {
		return ProgramRecord.class;
	}

	/**
	 * The column <code>first.program.id</code>. system id for this program
	 */
	public final TableField<ProgramRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "system id for this program");

	/**
	 * The column <code>first.program.name</code>. Display name for this program
	 */
	public final TableField<ProgramRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "Display name for this program");

	/**
	 * The column <code>first.program.short_name</code>. symbolic / abbreviate name used in program searches
	 */
	public final TableField<ProgramRecord, String[]> SHORT_NAME = createField("short_name", org.jooq.impl.SQLDataType.VARCHAR.getArrayDataType(), this, "symbolic / abbreviate name used in program searches");

	/**
	 * The column <code>first.program.membership</code>. Student body participation in this program
	 */
	public final TableField<ProgramRecord, String[]> MEMBERSHIP = createField("membership", org.jooq.impl.SQLDataType.VARCHAR.getArrayDataType(), this, "Student body participation in this program");

	/**
	 * The column <code>first.program.info</code>. Info for this program
	 */
	public final TableField<ProgramRecord, Object> INFO = createField("info", org.jooq.impl.DefaultDataType.getDefaultDataType("USER-DEFINED"), this, "Info for this program");

	/**
	 * Create a <code>first.program</code> table reference
	 */
	public Program() {
		this("program", null);
	}

	/**
	 * Create an aliased <code>first.program</code> table reference
	 */
	public Program(String alias) {
		this(alias, PROGRAM);
	}

	private Program(String alias, Table<ProgramRecord> aliased) {
		this(alias, aliased, null);
	}

	private Program(String alias, Table<ProgramRecord> aliased, Field<?>[] parameters) {
		super(alias, First.FIRST, aliased, parameters, "A program is a sub-organization of FIRST that describes the type of games that will be played and the \ntypes of participants.");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ProgramRecord, Integer> getIdentity() {
		return Keys.IDENTITY_PROGRAM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ProgramRecord> getPrimaryKey() {
		return Keys.PROGRAMS_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ProgramRecord>> getKeys() {
		return Arrays.<UniqueKey<ProgramRecord>>asList(Keys.PROGRAMS_PK, Keys.PROGRAM_SHORT_NAME_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Program as(String alias) {
		return new Program(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Program rename(String name) {
		return new Program(name, null);
	}
}
