/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.technojays.first.jooq.Sequences;
import org.technojays.first.jooq.tables.Alliance;
import org.technojays.first.jooq.tables.AllianceRef;
import org.technojays.first.jooq.tables.AllianceType;
import org.technojays.first.jooq.tables.Ally;
import org.technojays.first.jooq.tables.AttributeType;
import org.technojays.first.jooq.tables.Award;
import org.technojays.first.jooq.tables.AwardType;
import org.technojays.first.jooq.tables.Competition;
import org.technojays.first.jooq.tables.Event;
import org.technojays.first.jooq.tables.Game;
import org.technojays.first.jooq.tables.Location;
import org.technojays.first.jooq.tables.Match;
import org.technojays.first.jooq.tables.MatchScore;
import org.technojays.first.jooq.tables.Program;
import org.technojays.first.jooq.tables.ScoreType;
import org.technojays.first.jooq.tables.Sponsor;
import org.technojays.first.jooq.tables.Team;
import org.technojays.first.jooq.tables.TeamAttribute;
import org.technojays.first.jooq.tables.TeamScore;
import org.technojays.first.jooq.tables.TeamSponsor;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class First extends SchemaImpl {

	private static final long serialVersionUID = -168177929;

	/**
	 * The reference instance of <code>first</code>
	 */
	public static final First FIRST = new First();

	/**
	 * No further instances allowed
	 */
	private First() {
		super("first");
	}

	@Override
	public final List<Sequence<?>> getSequences() {
		List result = new ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final List<Sequence<?>> getSequences0() {
		return Arrays.<Sequence<?>>asList(
			Sequences.ALLIANCE_REF_ID_SEQ,
			Sequences.ALLIANCE_TYPES_ID_SEQ,
			Sequences.ALLIANCES_ID_SEQ,
			Sequences.ALLIES_ID_SEQ,
			Sequences.ATTRIBUTE_TYPES_ID_SEQ,
			Sequences.AWARD_TYPE_ID_SEQ,
			Sequences.AWARDS_ID_SEQ,
			Sequences.COMPETITIONS_ID_SEQ,
			Sequences.EVENTS_ID_SEQ,
			Sequences.GAMES_ID_SEQ,
			Sequences.LOCATIONS_ID_SEQ,
			Sequences.MATCH_SCORES_ID_SEQ,
			Sequences.MATCHES_ID_SEQ,
			Sequences.PROGRAMS_ID_SEQ,
			Sequences.SCORE_TYPES_ID_SEQ,
			Sequences.SPONSORS_ID_SEQ,
			Sequences.TEAM_ATTRIBUTES_ID_SEQ,
			Sequences.TEAM_SCORES_ID_SEQ,
			Sequences.TEAM_SPONSORS_ID_SEQ,
			Sequences.TEAMS_ID_SEQ);
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Alliance.ALLIANCE,
			AllianceRef.ALLIANCE_REF,
			AllianceType.ALLIANCE_TYPE,
			Ally.ALLY,
			AttributeType.ATTRIBUTE_TYPE,
			Award.AWARD,
			AwardType.AWARD_TYPE,
			Competition.COMPETITION,
			Event.EVENT,
			Game.GAME,
			Location.LOCATION,
			Match.MATCH,
			MatchScore.MATCH_SCORE,
			Program.PROGRAM,
			ScoreType.SCORE_TYPE,
			Sponsor.SPONSOR,
			Team.TEAM,
			TeamAttribute.TEAM_ATTRIBUTE,
			TeamScore.TEAM_SCORE,
			TeamSponsor.TEAM_SPONSOR);
	}
}
