/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Alliance types for FIRST programs
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "alliance_type", schema = "first")
public interface IAllianceType extends Serializable {

	/**
	 * Setter for <code>first.alliance_type.id</code>. System id for alliance type
	 */
	public IAllianceType setId(Integer value);

	/**
	 * Getter for <code>first.alliance_type.id</code>. System id for alliance type
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	public Integer getId();

	/**
	 * Setter for <code>first.alliance_type.name</code>. Name for alliance type
	 */
	public IAllianceType setName(String value);

	/**
	 * Getter for <code>first.alliance_type.name</code>. Name for alliance type
	 */
	@Column(name = "name")
	public String getName();

	/**
	 * Setter for <code>first.alliance_type.short_name</code>. Short Name for alliance type
	 */
	public IAllianceType setShortName(String[] value);

	/**
	 * Getter for <code>first.alliance_type.short_name</code>. Short Name for alliance type
	 */
	@Column(name = "short_name", unique = true)
	public String[] getShortName();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IAllianceType
	 */
	public void from(org.technojays.first.jooq.tables.interfaces.IAllianceType from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IAllianceType
	 */
	public <E extends org.technojays.first.jooq.tables.interfaces.IAllianceType> E into(E into);
}
