/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Relationship between a match and a group of allies
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "alliance", schema = "first")
public interface IAlliance extends Serializable {

	/**
	 * Setter for <code>first.alliance.id</code>. system id for this alliance
	 */
	public IAlliance setId(Integer value);

	/**
	 * Getter for <code>first.alliance.id</code>. system id for this alliance
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	public Integer getId();

	/**
	 * Setter for <code>first.alliance.type</code>. type (color) for this alliance
	 */
	public IAlliance setType(Integer value);

	/**
	 * Getter for <code>first.alliance.type</code>. type (color) for this alliance
	 */
	@Column(name = "type", precision = 32)
	public Integer getType();

	/**
	 * Setter for <code>first.alliance.match_id</code>. system id for the associated match
	 */
	public IAlliance setMatchId(Integer value);

	/**
	 * Getter for <code>first.alliance.match_id</code>. system id for the associated match
	 */
	@Column(name = "match_id", precision = 32)
	public Integer getMatchId();

	/**
	 * Setter for <code>first.alliance.ally_ref</code>. ally->alliance reference for all teams that were a part of this alliance (sha from team numbers)
	 */
	public IAlliance setAllyRef(String value);

	/**
	 * Getter for <code>first.alliance.ally_ref</code>. ally->alliance reference for all teams that were a part of this alliance (sha from team numbers)
	 */
	@Column(name = "ally_ref")
	public String getAllyRef();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IAlliance
	 */
	public void from(org.technojays.first.jooq.tables.interfaces.IAlliance from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IAlliance
	 */
	public <E extends org.technojays.first.jooq.tables.interfaces.IAlliance> E into(E into);
}
