/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Relationship between a set of teams for an alliance
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "ally", schema = "first")
public interface IAlly extends Serializable {

	/**
	 * Setter for <code>first.ally.id</code>.
	 */
	public IAlly setId(Integer value);

	/**
	 * Getter for <code>first.ally.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	public Integer getId();

	/**
	 * Setter for <code>first.ally.team_id</code>.
	 */
	public IAlly setTeamId(Integer value);

	/**
	 * Getter for <code>first.ally.team_id</code>.
	 */
	@Column(name = "team_id", precision = 32)
	public Integer getTeamId();

	/**
	 * Setter for <code>first.ally.ally_ref</code>.
	 */
	public IAlly setAllyRef(String[] value);

	/**
	 * Getter for <code>first.ally.ally_ref</code>.
	 */
	@Column(name = "ally_ref")
	public String[] getAllyRef();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IAlly
	 */
	public void from(org.technojays.first.jooq.tables.interfaces.IAlly from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IAlly
	 */
	public <E extends org.technojays.first.jooq.tables.interfaces.IAlly> E into(E into);
}
