/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Attribute types in program
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "attribute_type", schema = "first")
public interface IAttributeType extends Serializable {

	/**
	 * Setter for <code>first.attribute_type.id</code>. system id for this attribute type
	 */
	public IAttributeType setId(Integer value);

	/**
	 * Getter for <code>first.attribute_type.id</code>. system id for this attribute type
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	public Integer getId();

	/**
	 * Setter for <code>first.attribute_type.info</code>. info for this attribute type
	 */
	public IAttributeType setInfo(Object value);

	/**
	 * Getter for <code>first.attribute_type.info</code>. info for this attribute type
	 */
	@Column(name = "info")
	public Object getInfo();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IAttributeType
	 */
	public void from(org.technojays.first.jooq.tables.interfaces.IAttributeType from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IAttributeType
	 */
	public <E extends org.technojays.first.jooq.tables.interfaces.IAttributeType> E into(E into);
}
