/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * A competition describes a Location, Game, and is held at an Event
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "competition", schema = "first")
public interface ICompetition extends Serializable {

	/**
	 * Setter for <code>first.competition.id</code>.
	 */
	public ICompetition setId(Integer value);

	/**
	 * Getter for <code>first.competition.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	public Integer getId();

	/**
	 * Setter for <code>first.competition.name</code>.
	 */
	public ICompetition setName(String value);

	/**
	 * Getter for <code>first.competition.name</code>.
	 */
	@Column(name = "name")
	public String getName();

	/**
	 * Setter for <code>first.competition.type_id</code>. comptetion type id
	 */
	public ICompetition setTypeId(Integer value);

	/**
	 * Getter for <code>first.competition.type_id</code>. comptetion type id
	 */
	@Column(name = "type_id", precision = 32)
	public Integer getTypeId();

	/**
	 * Setter for <code>first.competition.event_id</code>.
	 */
	public ICompetition setEventId(Integer value);

	/**
	 * Getter for <code>first.competition.event_id</code>.
	 */
	@Column(name = "event_id", precision = 32)
	public Integer getEventId();

	/**
	 * Setter for <code>first.competition.location_id</code>.
	 */
	public ICompetition setLocationId(Integer value);

	/**
	 * Getter for <code>first.competition.location_id</code>.
	 */
	@Column(name = "location_id", precision = 32)
	public Integer getLocationId();

	/**
	 * Setter for <code>first.competition.game_id</code>.
	 */
	public ICompetition setGameId(Integer value);

	/**
	 * Getter for <code>first.competition.game_id</code>.
	 */
	@Column(name = "game_id", precision = 32)
	public Integer getGameId();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface ICompetition
	 */
	public void from(org.technojays.first.jooq.tables.interfaces.ICompetition from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface ICompetition
	 */
	public <E extends org.technojays.first.jooq.tables.interfaces.ICompetition> E into(E into);
}
