/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * An event describes the timeframe for competitions and celebrations that 
 * are managed together
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "event", schema = "first")
public interface IEvent extends Serializable {

	/**
	 * Setter for <code>first.event.id</code>. event system id
	 */
	public IEvent setId(Integer value);

	/**
	 * Getter for <code>first.event.id</code>. event system id
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	public Integer getId();

	/**
	 * Setter for <code>first.event.name</code>. display name for event
	 */
	public IEvent setName(String value);

	/**
	 * Getter for <code>first.event.name</code>. display name for event
	 */
	@Column(name = "name")
	public String getName();

	/**
	 * Setter for <code>first.event.short_name</code>. Short name for event
	 */
	public IEvent setShortName(String[] value);

	/**
	 * Getter for <code>first.event.short_name</code>. Short name for event
	 */
	@Column(name = "short_name", unique = true)
	public String[] getShortName();

	/**
	 * Setter for <code>first.event.start_date</code>. start date of event
	 */
	public IEvent setStartDate(Timestamp value);

	/**
	 * Getter for <code>first.event.start_date</code>. start date of event
	 */
	@Column(name = "start_date")
	public Timestamp getStartDate();

	/**
	 * Setter for <code>first.event.end_date</code>. end date of event
	 */
	public IEvent setEndDate(Timestamp value);

	/**
	 * Getter for <code>first.event.end_date</code>. end date of event
	 */
	@Column(name = "end_date")
	public Timestamp getEndDate();

	/**
	 * Setter for <code>first.event.info</code>. event info
	 */
	public IEvent setInfo(Object value);

	/**
	 * Getter for <code>first.event.info</code>. event info
	 */
	@Column(name = "info")
	public Object getInfo();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IEvent
	 */
	public void from(org.technojays.first.jooq.tables.interfaces.IEvent from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IEvent
	 */
	public <E extends org.technojays.first.jooq.tables.interfaces.IEvent> E into(E into);
}
