/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Locations for program
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "location", schema = "first")
public interface ILocation extends Serializable {

	/**
	 * Setter for <code>first.location.id</code>. location system id
	 */
	public ILocation setId(Integer value);

	/**
	 * Getter for <code>first.location.id</code>. location system id
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	public Integer getId();

	/**
	 * Setter for <code>first.location.lng</code>.
	 */
	public ILocation setLng(Double value);

	/**
	 * Getter for <code>first.location.lng</code>.
	 */
	@Column(name = "lng", precision = 53)
	public Double getLng();

	/**
	 * Setter for <code>first.location.lat</code>.
	 */
	public ILocation setLat(Double value);

	/**
	 * Getter for <code>first.location.lat</code>.
	 */
	@Column(name = "lat", precision = 53)
	public Double getLat();

	/**
	 * Setter for <code>first.location.place_id</code>.
	 */
	public ILocation setPlaceId(Integer value);

	/**
	 * Getter for <code>first.location.place_id</code>.
	 */
	@Column(name = "place_id", unique = true, precision = 32)
	public Integer getPlaceId();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface ILocation
	 */
	public void from(org.technojays.first.jooq.tables.interfaces.ILocation from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface ILocation
	 */
	public <E extends org.technojays.first.jooq.tables.interfaces.ILocation> E into(E into);
}
