/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * Scores associated with a match
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "match_score", schema = "first", uniqueConstraints = {
	@UniqueConstraint(columnNames = {"match_id", "alliance_id", "score_type_id"})
})
public interface IMatchScore extends Serializable {

	/**
	 * Setter for <code>first.match_score.id</code>. system id for this match
	 */
	public IMatchScore setId(Integer value);

	/**
	 * Getter for <code>first.match_score.id</code>. system id for this match
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	public Integer getId();

	/**
	 * Setter for <code>first.match_score.match_id</code>. system id of the associated match
	 */
	public IMatchScore setMatchId(Integer value);

	/**
	 * Getter for <code>first.match_score.match_id</code>. system id of the associated match
	 */
	@Column(name = "match_id", precision = 32)
	public Integer getMatchId();

	/**
	 * Setter for <code>first.match_score.alliance_id</code>. system id of the associated alliance
	 */
	public IMatchScore setAllianceId(Integer value);

	/**
	 * Getter for <code>first.match_score.alliance_id</code>. system id of the associated alliance
	 */
	@Column(name = "alliance_id", precision = 32)
	public Integer getAllianceId();

	/**
	 * Setter for <code>first.match_score.score_type_id</code>. system id of the score type
	 */
	public IMatchScore setScoreTypeId(Integer value);

	/**
	 * Getter for <code>first.match_score.score_type_id</code>. system id of the score type
	 */
	@Column(name = "score_type_id", precision = 32)
	public Integer getScoreTypeId();

	/**
	 * Setter for <code>first.match_score.value</code>. score value
	 */
	public IMatchScore setValue(String[] value);

	/**
	 * Getter for <code>first.match_score.value</code>. score value
	 */
	@Column(name = "value")
	public String[] getValue();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IMatchScore
	 */
	public void from(org.technojays.first.jooq.tables.interfaces.IMatchScore from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IMatchScore
	 */
	public <E extends org.technojays.first.jooq.tables.interfaces.IMatchScore> E into(E into);
}
