/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * Describe a match where teams competed against each other
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "match", schema = "first", uniqueConstraints = {
	@UniqueConstraint(columnNames = {"competition_id", "match_number"})
})
public interface IMatch extends Serializable {

	/**
	 * Setter for <code>first.match.id</code>. system id for this match
	 */
	public IMatch setId(Integer value);

	/**
	 * Getter for <code>first.match.id</code>. system id for this match
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	public Integer getId();

	/**
	 * Setter for <code>first.match.match_number</code>. match number for the competition
	 */
	public IMatch setMatchNumber(Integer value);

	/**
	 * Getter for <code>first.match.match_number</code>. match number for the competition
	 */
	@Column(name = "match_number", precision = 32)
	public Integer getMatchNumber();

	/**
	 * Setter for <code>first.match.competition_id</code>. competition system id
	 */
	public IMatch setCompetitionId(Integer value);

	/**
	 * Getter for <code>first.match.competition_id</code>. competition system id
	 */
	@Column(name = "competition_id", precision = 32)
	public Integer getCompetitionId();

	/**
	 * Setter for <code>first.match.start_time</code>.  expected match start time
	 */
	public IMatch setStartTime(Timestamp value);

	/**
	 * Getter for <code>first.match.start_time</code>.  expected match start time
	 */
	@Column(name = "start_time")
	public Timestamp getStartTime();

	/**
	 * Setter for <code>first.match.end_time</code>. expected match end time
	 */
	public IMatch setEndTime(Timestamp value);

	/**
	 * Getter for <code>first.match.end_time</code>. expected match end time
	 */
	@Column(name = "end_time")
	public Timestamp getEndTime();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IMatch
	 */
	public void from(org.technojays.first.jooq.tables.interfaces.IMatch from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IMatch
	 */
	public <E extends org.technojays.first.jooq.tables.interfaces.IMatch> E into(E into);
}
