/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * A program is a sub-organization of FIRST that describes the type of games 
 * that will be played and the 
 * types of participants.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "program", schema = "first")
public interface IProgram extends Serializable {

	/**
	 * Setter for <code>first.program.id</code>. system id for this program
	 */
	public IProgram setId(Integer value);

	/**
	 * Getter for <code>first.program.id</code>. system id for this program
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	public Integer getId();

	/**
	 * Setter for <code>first.program.name</code>. Display name for this program
	 */
	public IProgram setName(String value);

	/**
	 * Getter for <code>first.program.name</code>. Display name for this program
	 */
	@Column(name = "name")
	public String getName();

	/**
	 * Setter for <code>first.program.short_name</code>. symbolic / abbreviate name used in program searches
	 */
	public IProgram setShortName(String[] value);

	/**
	 * Getter for <code>first.program.short_name</code>. symbolic / abbreviate name used in program searches
	 */
	@Column(name = "short_name", unique = true)
	public String[] getShortName();

	/**
	 * Setter for <code>first.program.membership</code>. Student body participation in this program
	 */
	public IProgram setMembership(String[] value);

	/**
	 * Getter for <code>first.program.membership</code>. Student body participation in this program
	 */
	@Column(name = "membership")
	public String[] getMembership();

	/**
	 * Setter for <code>first.program.info</code>. Info for this program
	 */
	public IProgram setInfo(Object value);

	/**
	 * Getter for <code>first.program.info</code>. Info for this program
	 */
	@Column(name = "info")
	public Object getInfo();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IProgram
	 */
	public void from(org.technojays.first.jooq.tables.interfaces.IProgram from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IProgram
	 */
	public <E extends org.technojays.first.jooq.tables.interfaces.IProgram> E into(E into);
}
