/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * A team associated with a specific FIRST program
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "team", schema = "first")
public interface ITeam extends Serializable {

	/**
	 * Setter for <code>first.team.id</code>. system id forteam
	 */
	public ITeam setId(Integer value);

	/**
	 * Getter for <code>first.team.id</code>. system id forteam
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	public Integer getId();

	/**
	 * Setter for <code>first.team.program_id</code>. system id for the associated program
	 */
	public ITeam setProgramId(Integer value);

	/**
	 * Getter for <code>first.team.program_id</code>. system id for the associated program
	 */
	@Column(name = "program_id", precision = 32)
	public Integer getProgramId();

	/**
	 * Setter for <code>first.team.number</code>. number for this team
	 */
	public ITeam setNumber(Integer value);

	/**
	 * Getter for <code>first.team.number</code>. number for this team
	 */
	@Column(name = "number", unique = true, precision = 32)
	public Integer getNumber();

	/**
	 * Setter for <code>first.team.name</code>.  name for this team
	 */
	public ITeam setName(String value);

	/**
	 * Getter for <code>first.team.name</code>.  name for this team
	 */
	@Column(name = "name")
	public String getName();

	/**
	 * Setter for <code>first.team.short_name</code>. Team Short Name
	 */
	public ITeam setShortName(String value);

	/**
	 * Getter for <code>first.team.short_name</code>. Team Short Name
	 */
	@Column(name = "short_name")
	public String getShortName();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface ITeam
	 */
	public void from(org.technojays.first.jooq.tables.interfaces.ITeam from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface ITeam
	 */
	public <E extends org.technojays.first.jooq.tables.interfaces.ITeam> E into(E into);
}
