/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Attributes associated with a FIRST team
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "team_attribute", schema = "first")
public interface ITeamAttribute extends Serializable {

	/**
	 * Setter for <code>first.team_attribute.id</code>. system id for this attribute
	 */
	public ITeamAttribute setId(Integer value);

	/**
	 * Getter for <code>first.team_attribute.id</code>. system id for this attribute
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	public Integer getId();

	/**
	 * Setter for <code>first.team_attribute.team_id</code>. system id for associated team
	 */
	public ITeamAttribute setTeamId(Integer value);

	/**
	 * Getter for <code>first.team_attribute.team_id</code>. system id for associated team
	 */
	@Column(name = "team_id", unique = true, precision = 32)
	public Integer getTeamId();

	/**
	 * Setter for <code>first.team_attribute.attributes</code>. attributes
	 */
	public ITeamAttribute setAttributes(Object value);

	/**
	 * Getter for <code>first.team_attribute.attributes</code>. attributes
	 */
	@Column(name = "attributes")
	public Object getAttributes();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface ITeamAttribute
	 */
	public void from(org.technojays.first.jooq.tables.interfaces.ITeamAttribute from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface ITeamAttribute
	 */
	public <E extends org.technojays.first.jooq.tables.interfaces.ITeamAttribute> E into(E into);
}
