/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * Scores associated with a FIRST team during a match at a competition
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "team_score", schema = "first", uniqueConstraints = {
	@UniqueConstraint(columnNames = {"team_id", "match_id", "score_type_id"})
})
public interface ITeamScore extends Serializable {

	/**
	 * Setter for <code>first.team_score.id</code>. system id for this score
	 */
	public ITeamScore setId(Integer value);

	/**
	 * Getter for <code>first.team_score.id</code>. system id for this score
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	public Integer getId();

	/**
	 * Setter for <code>first.team_score.team_id</code>. system id for the associated team
	 */
	public ITeamScore setTeamId(Integer value);

	/**
	 * Getter for <code>first.team_score.team_id</code>. system id for the associated team
	 */
	@Column(name = "team_id", precision = 32)
	public Integer getTeamId();

	/**
	 * Setter for <code>first.team_score.match_id</code>. system id for the associated match
	 */
	public ITeamScore setMatchId(Integer value);

	/**
	 * Getter for <code>first.team_score.match_id</code>. system id for the associated match
	 */
	@Column(name = "match_id", precision = 32)
	public Integer getMatchId();

	/**
	 * Setter for <code>first.team_score.score_type_id</code>. system id for the associated score type
	 */
	public ITeamScore setScoreTypeId(Integer value);

	/**
	 * Getter for <code>first.team_score.score_type_id</code>. system id for the associated score type
	 */
	@Column(name = "score_type_id", precision = 32)
	public Integer getScoreTypeId();

	/**
	 * Setter for <code>first.team_score.value</code>. score value
	 */
	public ITeamScore setValue(String[] value);

	/**
	 * Getter for <code>first.team_score.value</code>. score value
	 */
	@Column(name = "value")
	public String[] getValue();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface ITeamScore
	 */
	public void from(org.technojays.first.jooq.tables.interfaces.ITeamScore from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface ITeamScore
	 */
	public <E extends org.technojays.first.jooq.tables.interfaces.ITeamScore> E into(E into);
}
