/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.technojays.first.jooq.First;
import org.technojays.first.jooq.Keys;
import org.technojays.first.jooq.tables.records.CompetitionRecord;


/**
 * A competition describes a Location, Game, and is held at an Event
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Competition extends TableImpl<CompetitionRecord> {

	private static final long serialVersionUID = 544715333;

	/**
	 * The reference instance of <code>first.competition</code>
	 */
	public static final Competition COMPETITION = new Competition();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CompetitionRecord> getRecordType() {
		return CompetitionRecord.class;
	}

	/**
	 * The column <code>first.competition.id</code>.
	 */
	public final TableField<CompetitionRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>first.competition.name</code>.
	 */
	public final TableField<CompetitionRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>first.competition.type_id</code>. comptetion type id
	 */
	public final TableField<CompetitionRecord, Integer> TYPE_ID = createField("type_id", org.jooq.impl.SQLDataType.INTEGER, this, "comptetion type id");

	/**
	 * The column <code>first.competition.event_id</code>.
	 */
	public final TableField<CompetitionRecord, Integer> EVENT_ID = createField("event_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>first.competition.location_id</code>.
	 */
	public final TableField<CompetitionRecord, Integer> LOCATION_ID = createField("location_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>first.competition.game_id</code>.
	 */
	public final TableField<CompetitionRecord, Integer> GAME_ID = createField("game_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>first.competition</code> table reference
	 */
	public Competition() {
		this("competition", null);
	}

	/**
	 * Create an aliased <code>first.competition</code> table reference
	 */
	public Competition(String alias) {
		this(alias, COMPETITION);
	}

	private Competition(String alias, Table<CompetitionRecord> aliased) {
		this(alias, aliased, null);
	}

	private Competition(String alias, Table<CompetitionRecord> aliased, Field<?>[] parameters) {
		super(alias, First.FIRST, aliased, parameters, "A competition describes a Location, Game, and is held at an Event");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<CompetitionRecord, Integer> getIdentity() {
		return Keys.IDENTITY_COMPETITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CompetitionRecord> getPrimaryKey() {
		return Keys.COMPETITIONS_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CompetitionRecord>> getKeys() {
		return Arrays.<UniqueKey<CompetitionRecord>>asList(Keys.COMPETITIONS_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Competition as(String alias) {
		return new Competition(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Competition rename(String name) {
		return new Competition(name, null);
	}
}
