/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.technojays.first.jooq.First;
import org.technojays.first.jooq.Keys;
import org.technojays.first.jooq.tables.records.GameRecord;


/**
 * A game describes a specific set of rules and competitions for a program 
 * and its teams. It has a period of time 
 * associated with it.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Game extends TableImpl<GameRecord> {

	private static final long serialVersionUID = 1036295690;

	/**
	 * The reference instance of <code>first.game</code>
	 */
	public static final Game GAME = new Game();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<GameRecord> getRecordType() {
		return GameRecord.class;
	}

	/**
	 * The column <code>first.game.id</code>.
	 */
	public final TableField<GameRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>first.game.name</code>.
	 */
	public final TableField<GameRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>first.game.short_name</code>.
	 */
	public final TableField<GameRecord, String[]> SHORT_NAME = createField("short_name", org.jooq.impl.SQLDataType.VARCHAR.getArrayDataType(), this, "");

	/**
	 * The column <code>first.game.program_id</code>. system id of associated program
	 */
	public final TableField<GameRecord, Integer> PROGRAM_ID = createField("program_id", org.jooq.impl.SQLDataType.INTEGER, this, "system id of associated program");

	/**
	 * The column <code>first.game.start_date</code>. Game start date
	 */
	public final TableField<GameRecord, Timestamp> START_DATE = createField("start_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "Game start date");

	/**
	 * The column <code>first.game.end_date</code>. end date of season
	 */
	public final TableField<GameRecord, Timestamp> END_DATE = createField("end_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "end date of season");

	/**
	 * Create a <code>first.game</code> table reference
	 */
	public Game() {
		this("game", null);
	}

	/**
	 * Create an aliased <code>first.game</code> table reference
	 */
	public Game(String alias) {
		this(alias, GAME);
	}

	private Game(String alias, Table<GameRecord> aliased) {
		this(alias, aliased, null);
	}

	private Game(String alias, Table<GameRecord> aliased, Field<?>[] parameters) {
		super(alias, First.FIRST, aliased, parameters, "A game describes a specific set of rules and competitions for a program and its teams. It has a period of time \nassociated with it.");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<GameRecord, Integer> getIdentity() {
		return Keys.IDENTITY_GAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<GameRecord> getPrimaryKey() {
		return Keys.GAMES_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<GameRecord>> getKeys() {
		return Arrays.<UniqueKey<GameRecord>>asList(Keys.GAMES_PK, Keys.GAMES_SHORT_NAME_UNIQUES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Game as(String alias) {
		return new Game(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Game rename(String name) {
		return new Game(name, null);
	}
}
