/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.technojays.first.jooq.First;
import org.technojays.first.jooq.Keys;
import org.technojays.first.jooq.tables.records.MatchRecord;


/**
 * Describe a match where teams competed against each other
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Match extends TableImpl<MatchRecord> {

	private static final long serialVersionUID = 422464795;

	/**
	 * The reference instance of <code>first.match</code>
	 */
	public static final Match MATCH = new Match();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<MatchRecord> getRecordType() {
		return MatchRecord.class;
	}

	/**
	 * The column <code>first.match.id</code>. system id for this match
	 */
	public final TableField<MatchRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "system id for this match");

	/**
	 * The column <code>first.match.match_number</code>. match number for the competition
	 */
	public final TableField<MatchRecord, Integer> MATCH_NUMBER = createField("match_number", org.jooq.impl.SQLDataType.INTEGER, this, "match number for the competition");

	/**
	 * The column <code>first.match.competition_id</code>. competition system id
	 */
	public final TableField<MatchRecord, Integer> COMPETITION_ID = createField("competition_id", org.jooq.impl.SQLDataType.INTEGER, this, "competition system id");

	/**
	 * The column <code>first.match.start_time</code>.  expected match start time
	 */
	public final TableField<MatchRecord, Timestamp> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, " expected match start time");

	/**
	 * The column <code>first.match.end_time</code>. expected match end time
	 */
	public final TableField<MatchRecord, Timestamp> END_TIME = createField("end_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "expected match end time");

	/**
	 * Create a <code>first.match</code> table reference
	 */
	public Match() {
		this("match", null);
	}

	/**
	 * Create an aliased <code>first.match</code> table reference
	 */
	public Match(String alias) {
		this(alias, MATCH);
	}

	private Match(String alias, Table<MatchRecord> aliased) {
		this(alias, aliased, null);
	}

	private Match(String alias, Table<MatchRecord> aliased, Field<?>[] parameters) {
		super(alias, First.FIRST, aliased, parameters, "Describe a match where teams competed against each other\n");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<MatchRecord, Integer> getIdentity() {
		return Keys.IDENTITY_MATCH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<MatchRecord> getPrimaryKey() {
		return Keys.MATCHES_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<MatchRecord>> getKeys() {
		return Arrays.<UniqueKey<MatchRecord>>asList(Keys.MATCHES_PK, Keys.MATCH_UNIQUENESS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Match as(String alias) {
		return new Match(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Match rename(String name) {
		return new Match(name, null);
	}
}
