/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.technojays.first.jooq.First;
import org.technojays.first.jooq.Keys;
import org.technojays.first.jooq.tables.records.ScoreTypeRecord;


/**
 * Types of scores associated with matches
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScoreType extends TableImpl<ScoreTypeRecord> {

	private static final long serialVersionUID = 1859769434;

	/**
	 * The reference instance of <code>first.score_type</code>
	 */
	public static final ScoreType SCORE_TYPE = new ScoreType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ScoreTypeRecord> getRecordType() {
		return ScoreTypeRecord.class;
	}

	/**
	 * The column <code>first.score_type.id</code>. system id for this score type
	 */
	public final TableField<ScoreTypeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "system id for this score type");

	/**
	 * The column <code>first.score_type.info</code>. info for this match score
	 */
	public final TableField<ScoreTypeRecord, Object> INFO = createField("info", org.jooq.impl.DefaultDataType.getDefaultDataType("USER-DEFINED"), this, "info for this match score");

	/**
	 * Create a <code>first.score_type</code> table reference
	 */
	public ScoreType() {
		this("score_type", null);
	}

	/**
	 * Create an aliased <code>first.score_type</code> table reference
	 */
	public ScoreType(String alias) {
		this(alias, SCORE_TYPE);
	}

	private ScoreType(String alias, Table<ScoreTypeRecord> aliased) {
		this(alias, aliased, null);
	}

	private ScoreType(String alias, Table<ScoreTypeRecord> aliased, Field<?>[] parameters) {
		super(alias, First.FIRST, aliased, parameters, "Types of scores associated with matches");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ScoreTypeRecord, Integer> getIdentity() {
		return Keys.IDENTITY_SCORE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ScoreTypeRecord> getPrimaryKey() {
		return Keys.MATCH_SCORE_TYPE_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ScoreTypeRecord>> getKeys() {
		return Arrays.<UniqueKey<ScoreTypeRecord>>asList(Keys.MATCH_SCORE_TYPE_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScoreType as(String alias) {
		return new ScoreType(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ScoreType rename(String name) {
		return new ScoreType(name, null);
	}
}
