/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.technojays.first.jooq.First;
import org.technojays.first.jooq.Keys;
import org.technojays.first.jooq.tables.records.TeamScoreRecord;


/**
 * Scores associated with a FIRST team during a match at a competition
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamScore extends TableImpl<TeamScoreRecord> {

	private static final long serialVersionUID = -870499007;

	/**
	 * The reference instance of <code>first.team_score</code>
	 */
	public static final TeamScore TEAM_SCORE = new TeamScore();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TeamScoreRecord> getRecordType() {
		return TeamScoreRecord.class;
	}

	/**
	 * The column <code>first.team_score.id</code>. system id for this score
	 */
	public final TableField<TeamScoreRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "system id for this score");

	/**
	 * The column <code>first.team_score.team_id</code>. system id for the associated team
	 */
	public final TableField<TeamScoreRecord, Integer> TEAM_ID = createField("team_id", org.jooq.impl.SQLDataType.INTEGER, this, "system id for the associated team");

	/**
	 * The column <code>first.team_score.match_id</code>. system id for the associated match
	 */
	public final TableField<TeamScoreRecord, Integer> MATCH_ID = createField("match_id", org.jooq.impl.SQLDataType.INTEGER, this, "system id for the associated match");

	/**
	 * The column <code>first.team_score.score_type_id</code>. system id for the associated score type
	 */
	public final TableField<TeamScoreRecord, Integer> SCORE_TYPE_ID = createField("score_type_id", org.jooq.impl.SQLDataType.INTEGER, this, "system id for the associated score type");

	/**
	 * The column <code>first.team_score.value</code>. score value
	 */
	public final TableField<TeamScoreRecord, String[]> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR.getArrayDataType(), this, "score value");

	/**
	 * Create a <code>first.team_score</code> table reference
	 */
	public TeamScore() {
		this("team_score", null);
	}

	/**
	 * Create an aliased <code>first.team_score</code> table reference
	 */
	public TeamScore(String alias) {
		this(alias, TEAM_SCORE);
	}

	private TeamScore(String alias, Table<TeamScoreRecord> aliased) {
		this(alias, aliased, null);
	}

	private TeamScore(String alias, Table<TeamScoreRecord> aliased, Field<?>[] parameters) {
		super(alias, First.FIRST, aliased, parameters, "Scores associated with a FIRST team during a match at a competition\n");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<TeamScoreRecord, Integer> getIdentity() {
		return Keys.IDENTITY_TEAM_SCORE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TeamScoreRecord> getPrimaryKey() {
		return Keys.TEAM_SCORES_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TeamScoreRecord>> getKeys() {
		return Arrays.<UniqueKey<TeamScoreRecord>>asList(Keys.TEAM_SCORES_PK, Keys.TEAM_SCORE_UNIQUENESS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeamScore as(String alias) {
		return new TeamScore(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TeamScore rename(String name) {
		return new TeamScore(name, null);
	}
}
