/**
 * This class is generated by jOOQ
 */
package org.technojays.first.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.technojays.first.jooq.First;
import org.technojays.first.jooq.Keys;
import org.technojays.first.jooq.tables.records.TeamSponsorRecord;


/**
 * Sponsors associated with a FIRST team for a given game (season)
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamSponsor extends TableImpl<TeamSponsorRecord> {

	private static final long serialVersionUID = -1313660247;

	/**
	 * The reference instance of <code>first.team_sponsor</code>
	 */
	public static final TeamSponsor TEAM_SPONSOR = new TeamSponsor();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TeamSponsorRecord> getRecordType() {
		return TeamSponsorRecord.class;
	}

	/**
	 * The column <code>first.team_sponsor.id</code>. system id for this team sponsor
	 */
	public final TableField<TeamSponsorRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "system id for this team sponsor");

	/**
	 * The column <code>first.team_sponsor.team_id</code>. system id for the associated
	 */
	public final TableField<TeamSponsorRecord, Integer> TEAM_ID = createField("team_id", org.jooq.impl.SQLDataType.INTEGER, this, "system id for the associated");

	/**
	 * The column <code>first.team_sponsor.sponsor_id</code>. system id for the associated sponsor
	 */
	public final TableField<TeamSponsorRecord, Integer> SPONSOR_ID = createField("sponsor_id", org.jooq.impl.SQLDataType.INTEGER, this, "system id for the associated sponsor");

	/**
	 * The column <code>first.team_sponsor.game_id</code>. system id for the associated game
	 */
	public final TableField<TeamSponsorRecord, Integer> GAME_ID = createField("game_id", org.jooq.impl.SQLDataType.INTEGER, this, "system id for the associated game");

	/**
	 * Create a <code>first.team_sponsor</code> table reference
	 */
	public TeamSponsor() {
		this("team_sponsor", null);
	}

	/**
	 * Create an aliased <code>first.team_sponsor</code> table reference
	 */
	public TeamSponsor(String alias) {
		this(alias, TEAM_SPONSOR);
	}

	private TeamSponsor(String alias, Table<TeamSponsorRecord> aliased) {
		this(alias, aliased, null);
	}

	private TeamSponsor(String alias, Table<TeamSponsorRecord> aliased, Field<?>[] parameters) {
		super(alias, First.FIRST, aliased, parameters, "Sponsors associated with a FIRST team for a given game (season)");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<TeamSponsorRecord, Integer> getIdentity() {
		return Keys.IDENTITY_TEAM_SPONSOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TeamSponsorRecord> getPrimaryKey() {
		return Keys.TEAM_SPONSORS_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TeamSponsorRecord>> getKeys() {
		return Arrays.<UniqueKey<TeamSponsorRecord>>asList(Keys.TEAM_SPONSORS_PK, Keys.TEAM_SPONSOR_UNIQUENESS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeamSponsor as(String alias) {
		return new TeamSponsor(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TeamSponsor rename(String name) {
		return new TeamSponsor(name, null);
	}
}
